---
editor_options: 
  markdown: 
    wrap: 72
---

# **PRESENTACIÓN Y OBJETIVOS** {#flujo-turistico}

## **INTRODUCCIÓN: OBJETIVO DEL DOCUMENTO**

Este informe metodológico tiene como fin presentar las tareas, técnicas
y métodos que MacroConsulting utilizará para dar cumplimiento a lo
solicitado en El Pliego de Bases y Condiciones Particulares (en adelante
El Pliego) y en la propuesta de trabajo de MacroConsulting presentada
durante el Proceso Licitatorio (en adelante La Propuesta), estipulado
por el Concurso Público Nacional de Etapa Única No 28-0004-CPU19, con el
propósito de realizar la Encuesta de Viajes y Turismo (en adelante
EVyTH)[^objetivos-1]. Para el relevamiento y posterior estudio de los
viajes de los argentinos se hará uso de técnicas mundialmente aceptadas
y se considerará la experiencia acumulada en nuestro país. La propuesta
de trabajo sobre la que se propone llevar adelante la EVyTH, se
estructura sobre las siguientes pautas básicas:

[^objetivos-1]: El presente informe se enmarca dentro de los
    requerimientos exigidos por El Pliego (ver página 33).

1)  Diseño muestral en el cual se pautará el marco a utilizar, unidad de
    análisis, manejo de reemplazos, tamaño muestral, período de
    encuestamiento, etc.
2)  Procedimiento en el campo, meses de referencia, etc.
3)  Instrumento tecnológico para la recolección de datos, consistencia,
    almacenamiento, etc.
4)  Sistema de Información para seguimiento y constatación en tiempo
    real del campo.
5)  Metodología de validación e imputación de datos y calibración de la
    muestra.
6)  Análisis de resultados en tiempo real y elaboración mensual de
    informes con resultados de ondas (informes de anticipos y finales).
7)  Especificación y dimensionamiento de equipos de campo, metodológico,
    estadísticos, administrativo y coordinación.

En base a esta enumeración, el informe se ordena de la siguiente forma:
en el apartado a continuación se repasa los objetivos generales y
específicos de la EVyTH y sus antecedentes. Posteriormente se detallan
los aspectos metodológicos y técnicos sobre los que se estructura el
relevamiento encomendado. Luego, se presentan los resultados esperados
de la consultoría. Finalmente, en anexo se adjuntan algunos detalles
adicionales de la propuesta metodológica (descripción de la estructura
del Formulario Base, Metodología de Imputación, Manual del Encuestador,
Cuadernillo de Ejercicios -para el instructor o los encuestadores-,
Curriculums Vitae del personal clave, etc.).

## **OBJETIVOS DE LA EVYTH: SUS ANTECEDENTES**

Para definir adecuadamente el marco metodológico de la EVyTH deben
considerarse claramente sus objetivos y antecedentes. Con el fin de
delinear correctamente estos aspectos, MacroConsulting se ha basado en
El Pliego, en la propuesta realizada en la oferta presentada por
MacroConsulting durante el proceso licitatorio (en adelante, La Oferta),
en reuniones posteriores mantenidas con la contraparte técnica del
Ministerio de Turismo y Deportes de la Nación (en adelante, Organismo
Contratante), en la experiencia acumulada en la realización de encuestas
similares en Argentina y en la experiencia internacional en
relevamientos análogos.

Además, se ha ido ganando conocimiento y experiencia específica a partir
del desarrollo de las ediciones de la EVyTH del año 2006 (EVyTH-06, en
adelante), de los años 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
2019 y 2020.

### **OBJETIVOS DE LA EVYTH**

De acuerdo con el Pliego, el objetivo es "realizar la Encuesta de Viajes
y Turismo de los Hogares --EVyTH- durante doce ondas consecutivas, a
razón de una onda por mes calendario, para relevar los viajes turísticos
realizados, sus características, así como también las expectativas de
viajes durante los períodos relevantes (temporada invernal y
estival)"[^objetivos-2].

[^objetivos-2]: Ver hoja 25 de El Pliego.

Por lo tanto, se pretende con la EVyTH medir la evolución de los viajes
realizados por los hogares residentes en los grandes aglomerados urbanos
de Argentina en el periodo de referencia, las características de los
recorridos turísticos (lugares visitados, forma de alojamiento,
estadías, utilización de paquete turístico, medios de transporte, etc.),
los viajes a segundas viviendas, el gasto de cada uno de los viajes y
los aspectos socio- demográficos de los hogares viajeros (ingreso total
del hogar, ocupación principal del jefe de hogar, etc.).

Además, la EVyTH debe incluir también un estudio prospectivo al relevar
las expectativas de viajes durante los periodos de interés turístico
(viajes de los argentinos para las temporadas invernal y estival).

La telesis general de la EVyTH es complementar la información para
estimar la oferta y demanda de bienes y servicios turísticos a través de
medir el turismo de los residentes en Argentina (tanto Turismo Nacional
como Turismo Interno). A partir de esta encuesta se espera obtener
información desagregada del comportamiento turístico de los hogares de
nuestro país y así permitir el dimensionamiento, en términos económicos,
del peso del turismo interno en el conjunto del consumo de bienes y
servicios turísticos en la Argentina. Con dicha información se pueden
efectuar estudios analíticos de los diferentes determinantes de la
actividad turística de los residentes en nuestro país y, por tanto,
diseñar e implementar políticas públicas sectoriales con mayor eficacia
y eficiencia. En consecuencia, la información recolectada sirve para:

1)  Conocer y caracterizar al turismo nacional.
2)  Como insumo para estimaciones de los gastos de los hogares en viajes
    y turismo, esencialmente para la elaboración de la Cuenta Satélite
    de Turismo.
3)  Como instrumento de diseño de políticas de incentivo o fomento del
    turismo mediante el estudio de las características sociodemográficas
    de los hogares que viajan y los que no viajan, así como de las
    modalidades de los viajes.
4)  Medir la repercusión de determinadas políticas de promoción del
    turismo (por ejemplo, estudiar las consecuencias de la diagramación
    de los feriados nacionales).

El objetivo específico de la EVyTH es recolectar información a través de
una encuesta estructurada sobre técnicas mundialmente aceptadas y sobre
la experiencia acumulada en nuestro país. En particular, esta
experiencia se debe complementar con el conocimiento recabado por
MacroConsulting durante:

1)  la realización de la Prueba Piloto, que sirvió de base para definir
    y testear la metodología de relevamiento de la de la EVyTH,
2)  la EVyTH llevada a cabo entre febrero y abril de 2011 (en adelante,
    EVyT-11),
3)  la EVyTH realizada durante el año 2012 (en adelante, EVyTH-12),
4)  la EVyTH desarrollada durante el año 2013 (en adelante, EVyTH-13),
5)  la EVyTH desarrollada durante el año 2014 (en adelante, EVyTH-14),
6)  la EVyTH desarrollada durante el año 2015 (en adelante, EVyTH-15),
7)  la EVyTH desarrollada durante el año 2016 (en adelante, EVyTH-16),
8)  la EVyTH desarrollada durante el año 2017 (en adelante, EVyTH-17),
9)  la EVyTH desarrollada durante el año 2018 (en adelante, EVyTH-18),
10) la EVyTH desarrollada durante el año 2019 (en adelante, EVyTH-19),
11) la EVyTH desarrollada durante el año 2020 (en adelante, EVyTH-20).

Se anticipan a continuación, en una enumeración no taxativa, la
información que será recabada durante el operativo de campo:

-   La evolución de la cantidad de viajes realizados en el período de
    referencia.

-   Las características de los recorridos turísticos durante el período
    de referencia (lugares visitados, forma de alojamiento, estadías,
    utilización de paquete turístico, medios de transporte, etc.).

-   El uso de segundas viviendas y las características de los viajes
    realizados a ellas durante el período de referencia.

-   El gasto de cada uno de los viajes realizados en Argentina y en el
    exterior durante el período de referencia.

-   Las características sociodemográficas de las personas que realizan y
    no realizan viajes durante el periodo (edad, sexo, nivel educativo,
    condición de actividad) y de los hogares que ellas integran (lugar
    de residencia, nivel de ingreso, tamaño del hogar, sexo, edad, nivel
    educativo y condición de actividad del jefe).

-   Cantidad de personas y características de los viajes que realizarán
    o probablemente realizaron los turistas durante los fines de semana
    largo.

-   Flujo turístico esperado para fechas especiales (temporada de
    invierno y verano) en función de las expectativas de viaje.

En el Anexo a este documento se detalla el contenido del cuestionario a
implementar, el cual fue previamente validado con el personal técnico
del Organismo Contratante.

### **ANTECEDENTES DE LA EVYTH**

La EVyTH tiene como objetivo fundamental la caracterización de los
viajes que realizan y/o realizarán los miembros de los hogares
residentes en Argentina, para lo cual se releva dónde van, qué medios de
transporte utilizan, dónde se alojan, cuáles son los motivos por los que
viajan, cuánto gastan, qué opinión tienen sobre los lugares, etc. En
base a este objetivo, se pueden mencionar dos tipos de antecedentes que
servirán de fuentes para determinar el mejor diseño metodológico a
utilizar durante la EVyTH-21; a saber: antecedentes locales y
antecedentes internacionales.

#### **ANTECEDENTES LOCALES DE LA EVYTH**

Consecuentemente, con la importancia que el turismo adquirió en las
últimas décadas en términos sociales, culturales y económicos, diversos
países han procurado obtener información que permitiese mensurar y
caracterizar el fenómeno. Una de las herramientas fundamentales para
este objetivo lo constituyen las investigaciones cuantitativas
implementadas a partir de encuestas. Tal como ha sucedido en el caso
argentino desde inicios de este siglo, las primeras experiencias
estuvieron dirigidas a captar el turismo internacional[^objetivos-3] y a
mensurar la llegada de viajeros a las plazas hoteleras de las ciudades
más importantes y de los principales destinos turísticos[^objetivos-4].

[^objetivos-3]: Por ejemplo, la Encuesta de Turismo Internacional (ETI)
    que actualmente lleva adelante el Organismo Contratante
    conjuntamente con el INDEC.

[^objetivos-4]: En Argentina existe la Encuesta de Ocupación Hotelera
    (relevamiento realizado conjuntamente entre el Organismo Contratante
    y el INDEC).

Sin embargo, este tipo de investigaciones dejan abierta una importante
brecha en lo que refiere al conocimiento del comportamiento turístico de
las personas y su impacto socioeconómico, en particular en lo referido
al turismo interno, es decir, los viajes que los residentes de un país
realizan dentro de él, fundamentalmente viajes en los que el alojamiento
utilizado no es un establecimiento hotelero. Además, en estos
relevamientos es escasa la información relevada sobre las
características de los viajeros.

Primero a partir de módulos especiales en las encuestas de gastos o
presupuestos de los hogares (con el fin primordial de medir el gasto de
los hogares en turismo) y luego a partir de encuestas específicas, en
los últimos años han tenido lugar diversas experiencias cuyo objetivo
radica en cuantificar y caracterizar los viajes realizados, a partir de
encuestas a hogares.

En el caso argentino, la primera experiencia de este tipo fue realizada
en conjunto por el INDEC (Instituto Nacional de Estadística y Censos) y
la por entonces Secretaría de Turismo de la Nación. Dicha investigación,
la EVyTH-06, prácticamente sin antecedentes en la región, conjugaba las
ricas y extensas experiencias internacionales en la materia, en especial
de la FAMILITUR española, conjuntamente con la sólida trayectoria
técnica en la realización de encuestas a hogares del INDEC. La EVyTH-06
se configuró como una encuesta proyectada para dar cuenta, bajo las
recomendaciones técnicas de la Organización Mundial del Turismo, de las
particularidades de los viajes y el turismo que los residentes en el
país realizan.

La prueba piloto de la EVyTH-06 se llevó a cabo en 2005, y el
relevamiento de la encuesta definitiva se realizó entre fines de 2006 e
inicios de 2007, en 10.000 hogares residentes en las capitales de cada
una de las provincias y en los aglomerados que, sin ser capitales,
tuvieran 100.000 habitantes o más.

La segunda experiencia fue recabada a fines del año 2010. Este
relevamiento, denominado Prueba Piloto para la Encuesta de Turismo
Doméstico en Hogares Residentes, permitió la fijación de las bases
metodológicas para llevar adelante una nueva encuesta que permitiese
medir la evolución de los viajes realizados por los hogares residentes y
sus particularidades. La mencionada encuesta fue puesta en marcha en
junio de 2011 (luego de su correspondiente Prueba Piloto) y se concentró
en medir el período estival de ese mismo año (enero a marzo de 2011). Le
siguió un período de relevamiento adicional para computar los viajes y
sus características durante el periodo de abril. Posteriormente,
MacroConsulting articuló una nueva EVyTH para el periodo 2011/2012.
Aquí, además de relevar y caracterizar los viajes realizados durante los
dos meses calendario anterior al mes de relevamiento, se propuso agregar
el relevamiento de expectativas de viaje para fechas especiales y
realizar análisis adicionales. Por ejemplo, se realizó un estudio sobre
las características de los viajes con más de una etapa; también se
estudiaron los destinos turísticos más visitados entre enero y
septiembre de 2012, que sirvió como primera aproximación a la
distribución geográfica de los turistas argentinos; y finalmente, se
implementaron estudios particulares de las temporadas invernales y de
verano. Por último, durante los años 2013 a 2016, MacroConsulting llevó
a cabo la EVyTH, confeccionando informes de relevancia sustantiva para
la caracterización del turismo nacional como lo fueron el informe de
viajes multidestinos, el estudio sobre destinos turísticos, informe de
resultados anuales, entre otros.

Consecuentemente con estos antecedentes, el marco metodológico que se
propone seguir para esta versión "2021" de la EVyTH, está inspirado
primordialmente en las siguientes fuentes:

1)  La Encuesta de Viajes y Turismo en Hogares realizada conjuntamente
    por el Instituto Nacional de Estadística y Censos y la Secretaría de
    Turismo de la Nación durante el año 2006 (EVyTH-06).
2)  Los trabajos realizados a fines de 2010 para la Prueba Piloto para
    la Encuesta de Turismo Doméstico en Hogares Residentes (Prueba
    Piloto).
3)  La Encuesta de Turismo Doméstico en Hogares Residentes para medir el
    período estival de 2011 (la EVyTH-11).
4)  La Encuesta de Turismo Doméstico en Hogares Residentes para medir el
    período de abril de 2011.
5)  La Encuesta de Turismo Doméstico a Hogares Residentes para el
    periodo 2011/2012 (la EVyTH-12).
6)  La Encuesta de Viajes y Turismo de los Hogares (la EVyTH-13).
7)  La Encuesta de Viajes y Turismo de los Hogares (la EVyTH-14).
8)  La Encuesta de Viajes y Turismo de los Hogares (la EVyTH-15).
9)  La Encuesta de Viajes y Turismo de los Hogares (la EVyTH-16).
10) La Encuesta de Viajes y Turismo de los Hogares (la EVyTH-17).
11) La Encuesta de Viajes y Turismo de los Hogares (la EVyTH-18).
12) La Encuesta de Viajes y Turismo de los Hogares (la EVyTH-19).
13) La Encuesta de Viajes y Turismo de los Hogares (la EVyTH-20).

#### **ANTECEDENTES INTERNACIONALES DE LA EVYTH**

La relevancia de las encuestas continuas de turismo doméstico ha sido
recogida por la Organización Mundial del Turismo (OMT) cuando en el
párrafo 2.72 de las Recomendaciones Internacionales sobre Estadísticas
de Turismo 2008 se indica que "Las encuestas a hogares basadas en
muestras estratificadas usando criterios espaciales, demográficos y
socio- económicos puede ser un instrumento eficiente y apropiado para
medir la actividad del turismo doméstico y su gasto relacionado".

El órgano rector de la estadística de la Unión Económica Europea
(EUROSTAT), ha receptado estas recomendaciones exigiendo como Directiva
Comunitaria una encuesta de turismo interno para cada país miembro. De
esta forma, a modo de ejemplo, se pueden citar los casos de España (con
la "Familitur") y el Reino Unido (con la "United Kingdom Tourism
Survey").

A propósito de ello, se observa en el Cuadro 1, el resultado del
relevamiento realizado con el fin de identificar aquellos países que han
instrumentado encuestas de turismo similares a la EVyTH. Como se
observa, con color azul se han marcado aquellos países que miden el
Turismo Nacional a través de encuestas específicas de turismo, sin
perjuicio de que la frecuencia de las mediciones no necesariamente es
realizada con periodicidad mínima anual (es decir, en esta categoría
pueden encontrarse países que realizan solo esporádicamente encuestas
específicas de turismo). Entre estos países podemos citar a México,
China y Brasil[^objetivos-5]. La segunda clasificación (en color celeste
claro), contiene aquellos países que miden el Turismo Nacional,
periódicamente, con una frecuencia mínima anual. Sin embargo, dentro de
esta clasificación pueden hallarse países que no han implementado una
encuesta específica para medir el turismo (por ejemplo, algunos países
dentro de esta clasificación miden el turismo a través de encuestas
permanentes a hogares). Algunos de los países que se encuentran en esta
categoría son Croacia, Paraguay y Uruguay.

[^objetivos-5]: Por ejemplo, en Brasil existe una encuesta específica de
    turismo tendiente a medir el Turismo Nacional (la Estudio de Demanda
    Turística Nacional) cuya frecuencia no es, como mínimo, regularmente
    anual (en efecto, se cuentan con datos para los siguientes años:
    1998, 2002, 2006, 2007 y 2012).

La tercera clasificación, de color turquesa, es una intersección entre
las dos caracterizaciones antes mencionadas (es decir, entre el color
azul y color celeste claro).

Aquí se encuentran los países que miden el Turismo Nacional a través de
encuestas específicas de turismo y presentan, además, un relevamiento
periódico con una frecuencia como mínimo anual. Alguno de los países que
se encuentran dentro de este grupo son Argentina, Gran Bretaña, España y
Japón. La categoría restante, agrupa los países que no presentan
(publican) mediciones sobre Turismo Nacional.

Como se observa, entonces, esta Encuesta de Viajes y Turismo de los Hogares encargada por el Organismo Contratante coloca a la Argentina entre un conjunto de países selectos que han implementado encuestas específicas para medir y caracterizar el Turismo Nacional con una periodicidad mínima anual. Es relevante destacar que este esfuerzo por parte del Organismo Contratante, permite contar con información crucial para diseñar y evaluar la implementación de políticas de desarrollo turístico, al tiempo que constituye una valiosa información para los distintos actores del sector.

**Cuadro 1: Países que relevan Encuestas de Turismo Doméstico**




