---
editor_options: 
  markdown: 
    wrap: 72
---


# **Presentación y Objetivos** {#presentacion-objetivos}


## Objetivos de la EVyTH y antecedentes

El objetivo de la EVyTH es medir la evolución de los viajes realizados por los hogares residentes en los grandes aglomerados urbanos de Argentina en el periodo de referencia, las características de los recorridos turísticos (lugares visitados, forma de alojamiento, estadías, utilización de paquete turístico, medios de transporte, etc.), los viajes a segundas viviendas, el gasto de cada uno de los viajes y los aspectos socio-demográficos de los hogares viajeros (ingreso total del hogar, ocupación principal del jefe de hogar, etc.).

A partir de esta encuesta se obtiene información desagregada del comportamiento turístico de los hogares de nuestro país y permite el dimensionamiento, en términos económicos, del peso del turismo interno en el conjunto del consumo de bienes y servicios turísticos en la Argentina. Con dicha información se pueden efectuar estudios analíticos de los diferentes determinantes de la actividad turística de los residentes en nuestro país y, por tanto, diseñar e implementar políticas públicas sectoriales con mayor eficacia y eficiencia. En consecuencia, la información recolectada sirve para:

    1.	Conocer y caracterizar al turismo nacional.

    2.	Como insumo para estimaciones de los gastos de los hogares en viajes y turismo, esencialmente para la elaboración de la Cuenta Satélite de Turismo.

    3.	Como instrumento de diseño de políticas de incentivo o fomento del turismo mediante el estudio de las características sociodemográficas de los hogares que viajan y los que no viajan, así como de las modalidades de los viajes.

    4.	Medir la repercusión de determinadas políticas de promoción del turismo.

El objetivo específico de la EVyTH es recolectar información a través de una encuesta estructurada sobre técnicas mundialmente aceptadas y sobre la experiencia acumulada en nuestro país. 

Consecuentemente con la importancia que el turismo adquirió en las últimas décadas en términos sociales, culturales y económicos, diversos países han procurado obtener información que permitiese mensurar y caracterizar este fenómeno. Una de las herramientas fundamentales para este objetivo lo constituyen las investigaciones cuantitativas implementadas a partir de encuestas. Tal como ha sucedido en el caso argentino desde inicios de este siglo, las primeras experiencias estuvieron dirigidas a captar el turismo internacional [^presentacion-objetivos-1] y a mensurar la llegada de viajeros a las plazas hoteleras de las ciudades más importantes y de los principales destinos turísticos [^presentacion-objetivos-2] .

[^presentacion-objetivos-1]: La Encuesta de Turismo Internacional (ETI) que actualmente lleva adelante juntamente con el INDEC.

[^presentacion-objetivos-2]: La Encuesta de Ocupación Hotelera (EOH) que actualmente lleva adelante juntamente con el INDEC

Sin embargo, este tipo de investigaciones dejan abierta una importante brecha en lo que refiere al conocimiento del comportamiento turístico de las personas y su impacto socioeconómico, en particular en lo referido al turismo interno, es decir, los viajes que los residentes de un país realizan dentro de él, fundamentalmente viajes en los que el alojamiento utilizado no es un establecimiento hotelero. Además, en estos relevamientos es escasa la información relevada sobre las características de los viajeros.

Primero a partir de módulos especiales en las encuestas de gastos o presupuestos de los hogares (con el fin primordial de medir el gasto de los hogares en turismo) y luego a partir de encuestas específicas. En los últimos años han tenido lugar diversas experiencias cuyo objetivo radica en cuantificar y caracterizar los viajes realizados, a partir de encuestas a hogares.

En el caso argentino, la primera experiencia de este tipo fue realizada en conjunto por el INDEC (Instituto Nacional de Estadística y Censos) y la por entonces Secretaría de Turismo de la Nación. Dicha investigación, la EVyTH-06, prácticamente sin antecedentes en la región, conjugaba las ricas y extensas experiencias internacionales en la materia, en especial de la FAMILITUR española, conjuntamente con la sólida trayectoria técnica en la realización de encuestas a hogares del INDEC. La EVyTH-06 se configuró como una encuesta proyectada para dar cuenta, bajo las recomendaciones técnicas de la Organización Mundial del Turismo, de las particularidades de los viajes y el turismo que realizan los residentes en el país.

La prueba piloto de la EVyTH-06 se llevó a cabo en 2005, y el relevamiento de la encuesta definitiva se realizó entre fines de 2006 e inicios de 2007, en 10.000 hogares residentes en las capitales de cada una de las provincias y en los aglomerados definidos por la Encuesta Permanente de Hogares (EPH).

La segunda experiencia fue recabada a fines del año 2010. Este relevamiento, denominado Prueba Piloto para la Encuesta de Turismo Doméstico en Hogares Residentes, permitió la fijación de las bases metodológicas para llevar adelante una nueva encuesta que permitiese medir la evolución de los viajes realizados por los hogares residentes y sus particularidades. La mencionada encuesta fue puesta en marcha en junio de 2011 (luego de su correspondiente Prueba Piloto) y se concentró en medir el período estival de ese mismo año (enero a abril de 2011). Desde 2012 la encuesta es continua. 


