---
editor_options: 
  markdown: 
    wrap: sentence
---

# **PLANEAMIENTO DE LOS ASPECTOS METODOLÓGICOS Y TÉCNICOS DE LA EVYTH**

A continuación, se detallan los aspectos metodológicos sobre los cuales se estructurará el relevamiento de la EVyTH-21.
Por consiguiente, se brinda una descripción pormenorizada sobre la unidad de observación a considerar, el marco muestral a utilizar, el diseño muestral a adoptar, el proceso de calibración a implementar, etc.
Se pretende con este capítulo dar cumplimiento por El Pliego en términos de explicitar la metodología a utilizarse durante el relevamiento.
Además de prefijar el marco, creemos también importante el contenido de este capítulo con miras a asentar un precedente que sirva de legado para que futuros relevamientos puedan replicar la metodología y procedimientos involucrados en la toma de datos y su posterior procesamiento para así conservar la consistencia y consecuente comparabilidad de los resultados.

## **UNIDADES DE OBSERVACIÓN**

Siguiendo las definiciones establecidas por El Pliego (las que son tomadas, a su vez, de la Prueba Piloto, la EVyTH-11, la EVyTH-12, la EVyTH-13, la EVyTH-14, la EVyTH-15, la EVyTH- 16, la EVyTH-17, la EVyTH-18, la EVyTH-19 y la EVyTH-20), las unidades de observación de la EVyTH son las personas que residen en hogares particulares dentro del territorio argentino.
Se considera hogar particular a aquel hogar constituido por una persona o grupo de personas, parientes o no, que conviven en una misma vivienda bajo un régimen de tipo familiar y consumen alimentos con cargo al mismo presupuesto.
Asimismo, se considera miembros del hogar a las personas que habitan en una misma vivienda bajo un régimen de tipo familiar, comparten sus gastos de alimentación, habitan la vivienda desde hace 6 o más meses o, si viven en ella hace menos de 6 meses, han fijado o piensan fijar allí su residencia.

## **MARCO CONCEPTUAL: DEFINICIÓN DE VIAJE**

Siguiendo las definiciones habituales y las recomendaciones internacionales de la Organización Mundial del Turismo, a los efectos del relevamiento de la EVyTH, se define como viaje de turismo a todo aquel desplazamiento realizado por todos, algunos o al menos uno de los miembros del hogar fuera de su entorno habitual (las segundas viviendas por definición no forman parte).
Debe tenerse en cuenta que:

-   Debe tener una duración inferior a un año y quien viajó no haber fijado su residencia en el lugar de destino.

-   Comprende los traslados, estancias y todas las actividades que las personas realizan en el lugar de destino.

-   Puede haber ido a un sólo destino o haber tenido varias etapas.

Los motivos del viaje pueden ser esparcimiento, ocio o recreación; visita a familiares y amigos; negocios o motivos profesionales; estudios y formación; razones de salud, religión u otros (trámites, compras, etc.).

Se incluyen tanto los viajes en los que el viajero pernocta al menos una noche en el lugar visitado como las visitas de un día (excusiones sin pernocte).

Se considera viaje a todos los desplazamientos que cumplan con las condiciones enumeradas anteriormente y en los que hayan participado todos, algunos o uno de los miembros actuales del hogar encuestado.

El entorno habitual comprende la zona cercana al lugar de residencia habitual del hogar más todos los lugares visitados frecuentemente, aunque no sean cercanos a su lugar de residencia.
Operacionalmente, la distancia que abarca el entorno habitual se define como el radio de 20 Km.
desde la ciudad/localidad en que se encuentra la vivienda principal del hogar, a excepción del Gran Buenos Aires (la Ciudad Autónoma de Buenos Aires más los 24 Partidos que conforman el Conurbano de esta provincia), donde la distancia que determina el entorno habitual es el radio de 40 Km.
de la localidad donde reside habitualmente el hogar.
La frecuencia mínima de visita a un sitio, para que éste sea considerado como parte del entorno habitual, es de una vez por semana.
Por lo tanto, los viajes que aquí consideramos son los realizados a destinos ubicados a más de 20/40 Km.
de la localidad donde está la vivienda principal y que fueron visitados con una frecuencia no semanal.

En el caso de los desplazamientos internacionales, el criterio de distancia mínima es reemplazado por el de traspaso de la frontera administrativa.
No obstante, el criterio de frecuencia sigue rigiendo, por lo cual, si una persona habitualmente traspasa la frontera una o más veces por semana, se considera que estos desplazamientos son parte de su entorno habitual.

Un desplazamiento a un lugar fuera del entorno habitual, en términos de distancia y frecuencia, puede no ser un viaje.
Estas exclusiones rigen en todos los casos, incluso cuando el viaje se realice a una segunda vivienda del hogar[^planeamiento-de-los-aspectos-1].

[^planeamiento-de-los-aspectos-1]: Si una persona realizó un desplazamiento cuyo motivo principal fue trabajar como empleado de una empresa o institución residente en el lugar visitado (a cambio de un salario, se trate de un empleo en "blanco" o no) no se considerará visitante de ese lugar y, por tanto, no se registrará el viaje.
    No se considera "empleado" si quien viaja por trabajo brinda un servicio por el cual percibe honorarios, o bien si recibe dinero en concepto de "viáticos", es decir, una asignación para cubrir los gastos del viaje (pasajes, alojamiento, alimentación, etc.).
    Por ejemplo, no se consideran viajeros cuando son empleados en el lugar de destino:

    -   trabajadores en temporada en hoteles, explotaciones agropecuarias, etc.;

    -   trabajadores temporarios en internados, hospitales y similares;

    -   estudiantes que viajan por períodos inferiores a 12 meses y trabajan para mantenerse (tanto quienes reciben un salario por su trabajo como quienes ayudan a una familia en las labores de la casa y el cuidado de los niños a cambio de la estancia y el mantenimiento);

    -   quienes viajan como acompañantes (familiares, servicio doméstico, etc.) de aquellos que lo hacen por cualquiera de los motivos ya enunciados, aunque hayan realizado actividades turísticas.

    <!-- -->

        En cambio, si se consideran que realizaron viajes aquellas personas que viajaron por trabajo, pero no fueron empleados en el
        lugar de destino, por ejemplo:

    -   conferenciantes, artistas de espectáculos y consultores;\

    -   un abogado que defiende en un juicio a una persona o empresa del lugar visitado;

    -   un cirujano que viaja a realizar una operación por única vez.

        No se consideran viajes aquellos desplazamientos realizados por las personas para quienes el traslado es parte de su trabajo.

        Por ejemplo, los pilotos de avión, conductores de camión o de ómnibus de larga distancia, viajantes de comercio y similares (incluyendo personal de seguridad, de asistencia -- azafatas-, etc.).

El Cuadro 2 a continuación resume la definición de entorno habitual discutida anteriormente.

**Cuadro 2: Definición de Entorno Habitual**

## **UNIDADES DE ANÁLISIS**

El marco conceptual antes definido permitirá obtener conclusiones a partir de diversas unidades de análisis.
A continuación, se las repasan junto con una breve descripción de cada una de ellas:

-   *Hogar*: es la persona o grupo de personas, parientes o no, que habitan bajo un mismo techo en un régimen de tipo familiar; es decir, comparten sus gastos en alimentación con cargo a un mismo presupuesto.

-   *Persona*: cada uno de los individuos integrantes de un hogar.

-   *Viaje*: significa cada desplazamiento que realiza una persona fuera del entorno habitual pernoctando en el/los lugar/es de destino.

-   *Visita de un día*: es el recorrido de una persona fuera del entorno habitual sin pernoctar en el lugar de destino.

-   *Pernoctación*: se trata de una noche de alojamiento de una persona.

Ver en la sección 6.5.1 (el Manual del Encuestador) para más detalles de cada concepto.

## **UNIVERSO BAJO ESTUDIO**

Según lo estipulado por El Pliego, el universo bajo estudio de la encuesta serán los aglomerados urbanos que tengan más de 100.000 habitantes.
En aquellas provincias donde no haya ningún aglomerado que cumpla dicha condición, se incorporará el aglomerado compuesto por la capital de la misma[^planeamiento-de-los-aspectos-2].
Por lo tanto, se considerarán 32 aglomerados según la descripción que se anexa en el Cuadro 22 del Anexo.
Los aglomerados se agruparán en las siguientes Regiones[^planeamiento-de-los-aspectos-3],
[^planeamiento-de-los-aspectos-4]:

[^planeamiento-de-los-aspectos-2]: Se sigue aquí la metodología utilizada durante la EVyTH-06.

[^planeamiento-de-los-aspectos-3]: Las regiones están definidas a partir del criterio que la Secretaría de Turismo (y luego el Organismo Contratante) ha venido utilizando para sus relevamientos (EVyTH-06, Encuesta de Ocupación Hotelera, Plan Federal Estratégico de Turismo Sustentable, etc.).

[^planeamiento-de-los-aspectos-4]: Se debió decidir en qué regiones incluir los aglomerados urbanos "San Nicolás -- Villa Constitución" y "Viedma -- Carmen de Patagones" puesto que las ciudades se encuentran en distintas provincias y, por ende, en diferentes regiones (según la definición que sigue).
    Se incluye al primer aglomerado (San Nicolás -- Villa Constitución) en la Región Buenos Aires, mientras que el segundo (Viedma -- Carmen de Patagones), en la Región Patagonia.

-   Región Ciudad de Buenos Aires.

-   Partidos del Conurbano de la Provincia de Buenos Aires.

-   Región Interior de la Provincia de Buenos Aires: compuesto por todos los aglomerados pertenecientes a dicha Provincia, excepto Partidos del Conurbano de la Provincia de Buenos Aires.

-   Región Córdoba: compuesto por todos los aglomerados pertenecientes a la Provincia de Córdoba.

-   Región Litoral: compuesto por todos los aglomerados pertenecientes a las Provincias de Santa Fe, Entre Ríos, Corrientes, Misiones, Formosa y Chaco.

-   Región Norte: compuesto por todos los aglomerados pertenecientes a las provincias de Jujuy, Salta, Tucumán, Santiago del Estero, Catamarca y La Rioja.

-   Región Cuyo: compuesto por todos los aglomerados pertenecientes a las provincias de Mendoza, San Luis, San Juan.

-   Región Patagónica: compuesto por todos los aglomerados pertenecientes a las provincias de La Pampa, Neuquén, Río Negro, Chubut, Santa Cruz y Tierra del Fuego[^planeamiento-de-los-aspectos-5].

[^planeamiento-de-los-aspectos-5]: Cabe aclarar que se incluirán el aglomerado "San Nicolás -- Villa Constitución" en la Región Provincia de Buenos Aires, mientras que el aglomerado "Viedma -- Carmen de Patagones" será incluido en la Región Patagonia.

A continuación, se presenta un cuadro que, a modo ilustrativo, indica los aglomerados que serán relevados.
Para mayor detalle véase el Anexo.

**Cuadro 3: Mapa con los aglomerados capitales de provincia o aglomerados urbanos de más de 100.000 habitantes del universo bajo estudio**

## **DISEÑO MUESTRAL**

El diseño muestral a considerar durante el relevamiento de la EVyTH se estructura en las siguientes pautas:

1)  Cada una de las regiones definidas es considerará como estrato y se seleccionará muestras independientes en cada uno de ellos.
2)  El método de selección a implementar es el sistemático.
3)  Si fuera imposible disponer de información auxiliar que permita realizar estratificaciones socioeconómicas en cada una de las regiones, previo a la selección, se procederá a ordenar las bases de manera tal de salvar este inconveniente con el objetivo de lograr "una estratificación implícita".
4)  Cada región, entonces, se ordenará por Aglomerado -- Partido/Departamento -- Localidad -- Característica Telefónica.

## **TAMAÑO MUESTRALY MANEJO DE LOS REEMPLAZOS**

La Prueba Piloto de la EVyTH, contribuyó significativamente a probar numerosas cuestiones vinculadas al proceso de encuestamiento, a saber: tecnología a utilizar, dimensionamiento de equipos, delineamiento del cuestionario, etc.
Tuvo, también, un muy valioso aporte desde el punto de vista del muestreo.
En efecto, la Prueba Piloto estuvo centrada en probar si el padrón telefónico con el que se contó constituye un buen marco de muestreo para extraer la muestra definitiva.
Luego, la EVyTH-11 implementó la metodología especificada a partir de la Prueba Piloto y se concluyó que necesitan entre cinco y seis números telefónicos por hogar para obtener una encuesta efectiva.

Consecuentemente, en base a estos resultados y en cumplimiento con lo establecido por El Pliego[^planeamiento-de-los-aspectos-6], la EVyTH-21 considerará una muestra titular de 2.600 hogares distribuidos a lo largo de cada Región - Aglomerado -- Partido/Departamento - Localidad (ver Cuadro 3).
Asimismo, en caso de que la muestra titular no pueda ser completada (por ausencia de respondentes, rechazo a responder la encuesta o errores del marco), se seleccionarán, con el mismo diseño muestral, seis hogares adicionales como reemplazos por hogar titular[^planeamiento-de-los-aspectos-7]
. Los reemplazos deberán coincidir en la Región, Aglomerado, Partido/Departamento y Localidad y serán utilizados luego de, al menos, seis intentos de comunicación insatisfactorios con la muestra inicial
. En conclusión, se tomarán 6 reemplazos y, por lo tanto, la muestra tendrá un tamaño de 15.000 hogares con sus respectivos números de teléfono (por onda)
.

[^planeamiento-de-los-aspectos-6]: Véase Pliego página 28

[^planeamiento-de-los-aspectos-7]: La posibilidad de disponer de la Guía Telefónica Nacional actualizada reduce considerablemente este problema ya que, por ejemplo, elimina los teléfonos deshabilitados y, de ese modo, el relevamiento resulta más eficiente.

De esta forma, con el mecanismo de períodos de referencia y ventanas de observación que se implementará (ver más adelante sección 2.6.2), se logrará que, para un mes determinado, se duplique el tamaño de muestra (es decir, se relevarán 5.200 hogares)[^planeamiento-de-los-aspectos-8].
La muestra completa (incluyendo reemplazos) estará en constante disposición del Departamento de Estadísticas del Organismo Contratante bajo las reservas del secreto estadístico contemplado en El Pliego.

[^planeamiento-de-los-aspectos-8]: Esta metodología se inspira en la Familitur de España y sigue lo pautado por El Pliego.

Finalmente, en base a resultados de las experiencias anteriores de la Encuesta, y en cumplimiento con lo establecido por El Pliego, las expectativas de viajes para los periodos de alta demanda de turismo como el invierno y el verano considerarán una muestra titular de 1.500 hogares distribuidos a lo largo de cada Región - Aglomerado -- Partido/Departamento - Localidad.

### **MARCO DE MUESTREO**

La EVyTH se instrumentará a través de un sistema C.A.T.I. (Computer Assisted Telephone Interviewing).
Para ello, se utilizará como marco de muestreo la Guía Telefónica Nacional (GTN) del año 2011 (actualizada a 2012/13/14/15/16/17/18/19/20).
MacroConsulting cuenta con una Guía ya consistida y validada.

Los Licenciatarios de Telefonía Básica es la fuente consultada para obtener la GTN.
La GTN está compuesta por los siguientes campos:

-   Rubro/Actividad

-   Apellido y Nombre

-   Domicilio

-   Teléfono

-   CP

-   Ciudad

-   Localidad

-   Provincia

Con el fin de considerar únicamente aquellos registros que corresponden a los hogares (y no tener en cuenta comercios, empresas, entidades gubernamentales, etc.), se realizaron ciertos filtros a dicha base de datos.

-   En primer lugar, se eliminaron todos aquellos datos cuyo campo "Rubro/Actividad" no fuera "Part/Com".
    Luego se procedió a eliminar los registros en los que o bien la primera o bien la última palabra del campo "Apellido y Nombre" hicieran referencia a empresas, comercios, entes gubernamentales, etc.
    Por ejemplo, se descartaron aquellos datos cuya última palabra fuera "S.A.", "S.R.L.", etc., dado que hacen referencia a sociedades.
    Otros ejemplos son los registros cuya primera palabra del campo "Apellido y Nombre" fuera "Hospital", "Gobierno", etc.
    De esta forma se eliminaron gran parte de los datos que no correspondieran a hogares.

-   Se eliminaron los datos repetidos, considerándose como tales aquellos con un mismo nombre y dirección.

-   Finalmente, en el caso de la Ciudad Autónoma de Buenos Aires, se utilizó una base de datos de códigos postales mediante la cual se agregó a cada registro de la base de la GTN su barrio correspondiente.

-   En base a esta metodología se actualizó el Marco de Muestreo utilizado para la Prueba Piloto, la EVyTH-11, la EVyTH-12, EVyTH-13, EVyTH-14, EVyTH-15, EVyTH-16 EVyTH-17, EVyTH-18, EVyTH-19 y la EVyTH-20 para considerar los cambios y renovaciones que podrían haber ocurrido desde mediados de 2011 en adelante.

### **PERIODICIDAD, VENTANA DE OBSERVACIÓN, PERÍODOS DE REFERENCIA Y ESQUEMA DE ROTACIÓN MUESTRAL**

#### **PERIODICIDAD, VENTANA DE OBSERVACIÓN Y PERÍODOS DE REFERENCIA**

Para llevar adelante el campo de la EVyTH, siguiendo lo pautado por El Pliego, se propone utilizar una periodicidad de muestreo mensual; es decir, todos los meses se releva una muestra seleccionada de acuerdo a la metodología descripta anteriormente.

Además, se contemplará una ventana de observación[^planeamiento-de-los-aspectos-9] bimestral para los meses a ser relevados, es decir, períodos de recordación de dos meses consecutivos.
Las ventanas de observación de períodos cortos, como este caso, eliminan la necesidad de recordación por tiempos prolongados, lo que favorece la veracidad de la información.

[^planeamiento-de-los-aspectos-9]: El período para el cual se brinda información se denomina ventana de observación.

Tomar períodos bimestrales como ventanas de observación permite generar un sistema de solapamiento que brinda mayor robustez a las conclusiones que se alcancen.

Para dar mayor detalle del mecanismo a implementar en términos de ventanas de observación y solapamiento, se transcribe en el Cuadro 4, la conceptualización del esquema.

**Cuadro 4: Periodicidad, Ventana de Observación y Períodos de Referencia**

De acuerdo con El Pliego, la EVyTH debe desarrollarse "durante doce ondas consecutivas, a razón de una onda por mes calendario"[^planeamiento-de-los-aspectos-10].
El mes calendario de comienzo del relevamiento es marzo de 2021.
Por lo tanto, para ese mes (que sería la Onda 1 de la EVyTH-21), se encuestará la muestra (titular) de 2.600 hogares (con los remplazos que hicieran falta) y se consultará por los períodos de referencia correspondiente a los dos meses calendarios anteriores; es decir, enero y febrero de 2021.
Durante el segundo mes de relevamiento, abril de 2021 (Onda 2), se procederá de forma similar para los viajes realizados en los dos meses anteriores (febrero y marzo de 2021).
Consecuentemente el Mes 2 (abril de 2021) quedará "solapada" la muestra, habiéndose encuestado 5.200 hogares para este mes (es decir, luego del segundo mes de relevamiento).
De este modo se garantizará que, para las estimaciones contenidas en los informes correspondiente a cada mes, en el apartado de Anticipo Mensual (véase sección 3.1.1.1.1) serán obtenidas a partir de 2.600 encuestas efectivas, mientras que para las estimaciones mensuales finales la muestra quedará duplicada a 5.200 (lo que garantizará la robustez del resultado).
[^planeamiento-de-los-aspectos-11]

[^planeamiento-de-los-aspectos-10]: Véase Pliego pág.
    25.

[^planeamiento-de-los-aspectos-11]: Siguiendo lo especificado en El Pliego (ver página 29).

#### **ESQUEMA DE ROTACIÓN MUESTRAL**

Con el objetivo de mejorar la comparación interanual de las principales variables a relevar, se renovará periódicamente el conjunto de hogares a encuestar (panel de respondentes)[^planeamiento-de-los-aspectos-12].
Conceptualmente, el esquema de rotación de una encuesta tiene incidencia sobre los siguientes aspectos:

[^planeamiento-de-los-aspectos-12]: La forma en que se produce esta renovación se denomina esquema de rotación.

-   Precisión de las estimaciones del cambio entre dos períodos diferentes.

-   Precisión de las estimaciones obtenidas al agregar muestra.

-   Nivel de no respuesta (por cansancio del panel).

El solapamiento de las muestras entre dos períodos consecutivos (o sea el porcentaje de muestra en común) juega en sentido contrario para los primeros dos aspectos: si un esquema tiene un alto porcentaje de solapamiento entre un período y el siguiente, puede medir adecuadamente los cambios, pero disminuir su precisión para una agregación a lo largo de varios períodos.
Por el contrario, un bajo solapamiento mejora la precisión cuando se agrega muestra, pero disminuye la precisión de la estimación del cambio entre períodos sucesivos.

El objetivo primordial de la EVyTH es medir la evolución de los viajes que, es sabido, es una variable que presenta una gran estacionalidad.
Consecuentemente, la medición de la evolución no se realizará a partir de comparar dos meses consecutivos (excepto algunos meses en particular), sino que anualmente o agregando períodos (estival, invernal, etc.).

Tal como se describió anteriormente, de acuerdo a El Pliego, el manejo muestral exige escoger la muestra antes de cada mes de relevamiento de modo tal de obtener muestras independientes, pero solapadas.
El esquema de rotación que se implementará consistirá en incluir en la muestra del mes 1 del año t, la muestra titular de los hogares respondentes del mismo periodo (mes 1) del año anterior (t-1), no con el objetivo de estudiar el comportamiento de esos hogares en particular, sino de modo tal de hacer que las variaciones interanuales no presenten diferencias extremas[^planeamiento-de-los-aspectos-13].
De esta forma se maximiza la precisión en cuanto a los cambios suscitados entre un año y otro.
Un sistema de rotación muestral como este, permite evitar el cansancio del panel respondente ya que se repetirán los hogares luego de doce meses.
De esta manera, se logrará una mejor ponderación entre ganancia en precisión (al rotar la muestra) y medición del cambio entre dos períodos (dos años).

[^planeamiento-de-los-aspectos-13]: Este esquema ya fue propuesto como parte de La Oferta de MacroConsulting.

Es relevante señalar que durante la EVyTH-12 se llevó a cabo una prueba piloto de esta metodología "de panel" entre los meses de abril y mayo (ondas 3 y 4).
Los resultados fueron positivos ya que no se encontraron sesgos en las características de los respondentes[^planeamiento-de-los-aspectos-14], a la vez que se aumentó la tasa de efectividad de las encuestas[^planeamiento-de-los-aspectos-15]
. En efecto, en comparación con las ondas en las que no fue implementada esta metodología de panel (es decir, para las ondas 1 a 4 de la EVyTH-11 y ondas 1 y 2 de la EVyTH-12), la tasa de efectividad de encuesta para los hogares titulares durante las ondas en las que sí se adoptó, (es decir, ondas 3 y 4) fue del doble
. Mientras que se halló que poco más de dos de cada diez hogares de la muestra titular decidieron responder la encuesta en las primeras ondas, casi cinco de cada diez decidieron hacerlo en las ondas 3 y 4 durante el relevamiento de la EVyTH-12
. Además, se realizó un control por características sociodemográficas del miembro respondente para verificar que no se hubiera sesgado la muestra
. Las variables consideradas fueron
:

[^planeamiento-de-los-aspectos-14]: El control consistió en evaluar las características principales de los respondentes de la encuesta durante las primeras cuatro ondas de relevamiento del año 2011 y del año 2012.
    El objetivo fue estudiar si se producía algún sesgo demográfico al utilizar muestras panel.
    Los relevamientos de las ondas 3 y 4 (relevamientos de abril y mayo) de la EVyTH-12 fueron panel (incluyeron a los hogares respondentes del mismo periodo del año anterior), mientras que las ondas 1 y 2 (febrero y marzo) no lo fueron.

    Los resultados del estudio demostraron que no se encontraron variaciones significativas en ningunas de las variables estudiadas (edad promedio edad en tramos, relación de parentesco del miembro respondente con el jefe de hogar, asistencia a establecimiento educativo, máximo nivel educativo alcanzado, situación ocupacional) entre los meses con muestra panel y los meses sin muestra panel.

[^planeamiento-de-los-aspectos-15]: Se estudiaron las características de los respondentes no notándose diferencias estadísticamente significativas entre los respondentes que aceptaron ser encuestados el año anterior respecto del mismo grupo que aceptó ser encuestado en el 2012.

-   edad promedio del miembro respondente

-   jefe de hogar o relación de parentesco con el jefe de hogar

-   asistencia a establecimiento educativo

-   máximo nivel educativo alcanzado

-   situación ocupacional

El estudio arrojó el resultado antes comentado: no se encontraron mayores diferencias socio-económicas entre aquellos que accedieron a contestar las preguntas de esta edición de la encuesta con aquellos que lo hicieron en las ondas con distinta metodología.

## **CUESTIONARIO**

Siguiendo lo especificado por El Pliego[^planeamiento-de-los-aspectos-16] a continuación se expone el Cuestionario que se implementará durante el relevamiento de la EVyTH.
El mismo consiste en un Cuestionario Base (o sección "pétrea") que, básicamente, pretende relevar los viajes realizados en los últimos dos meses y un Cuestionario "ad-hoc" que tiene la función de captar eventuales viajes futuros para fechas especiales como son los periodos de Verano/Invierno.

[^planeamiento-de-los-aspectos-16]: El Pliego especifica: "Se anexa formulario base para el relevamiento de la encuesta mensual y el de expectativas de viajes.

    Los cambios en los formularios base, que no se deban a cambios en los períodos de referencia de las distintas ondas, se realizarán únicamente a solicitud del personal técnico de la Secretaría, aunque en la propuesta se podrán realizar sugerencias de modificación del formulario que serán consideradas al evaluar las ofertas" (ver hoja 30).

### **ANTECEDENTE DE LA ACTUAL EDICIÓN DE LA EVYTH**

El Cuestionario implementado en la EVyTH-06, constituyó el modelo sobre el cual se trabajó para llegar al cuestionario aplicado en la Prueba Piloto, en la EVyTH-11, en la EVyTH-12, en la EVyTH-13, en la EVyTH-14, en la EVyTH-15, EVyTH-16, en la EVyTH-17, en la EVyTH-18, en la EVyTH-19 y en la EVyTH-20 que son los antecedentes a la actual edición de la EVyTH.

Al observarse el Formulario anexado a El Pliego, se puede notar que la estructura conceptual del cuestionario ha perdurado desde su comienzo en 2010 aunque, sin embargo, seguramente fue preciso realizar algunas modificaciones atendiendo a situaciones de diversa índole[^planeamiento-de-los-aspectos-17].
Los cambios que ha sufrido el cuestionario se resumen a continuación y resultan en el Formulario Base anexado a este informe (ver sección 6.6).
[^planeamiento-de-los-aspectos-18]

[^planeamiento-de-los-aspectos-17]: Circunstancias a las que se le debe adicionar el hecho de que ahora el relevamiento es telefónico (a diferencia de la EVyTH-06, que se realizó cara a cara).

[^planeamiento-de-los-aspectos-18]: Este Formulario Base ya incorpora la actualización de los tramos de gastos (según tipo de viaje) y de ingreso (así como también los cambios necesarios a las preguntas de comportamiento turístico).

En primer lugar, al comenzar la edición 2012 de la EVyTH se incorporó un relevamiento "ad- hoc" (complementario al cuestionario básico) con el fin de relevar las expectativas de viaje de los hogares argentinos durante fechas especiales dentro de cada mes de relevamiento.

Para esta edición se anexa el formulario de expectativas para viajes de las temporadas de invierno y verano (ver sección 6.7).

En segundo lugar, durante la EVyTH-12, se incorporó al cuestionario base implementado durante la EVyTH-11, la categoría "educación especial sin nivel" a la pregunta de nivel educativo.
Esto permitió categorizar con mayor precisión a todos los encuestados.

En tercer lugar, se modificó la manera de formular algunas preguntas para hacerlas más comprensibles.
Por ejemplo, en la pregunta sobre duración del viaje de corta duración a segundas viviendas se remplazó "¿Cuántas noches pasaron en la vivienda?" por "¿Cuál fue la duración del viaje, desde que salieron hasta que regresaron a su hogar?" .

En cuarto lugar, se reemplazó en la pregunta "¿Qué medio de transporte utilizaron para ir hasta allá? La categoría "Automóvil o similar (propio)" por solo "automóvil", por prestarse a confusión.

En quinto lugar, en el bloque donde se indaga sobre las características de los miembros del hogar, se realizó una modificación respecto a las características ocupacionales del miembro del hogar.
Se cambió la categoría "jubilado/a" por "jubilado/a o pensionado/a".

En sexto lugar, se actualizaron los tramos de gasto e ingresos del hogar.
Debido a la evolución en el ingreso de los hogares y del consecuente gasto turístico, resultó necesario realizar un ajuste en los montos de tramos de gasto de total del viaje y del ingreso del hogar.
Además, se cuenta con información acumulada que permite realizar un análisis exhaustivo al interior de la propia fuente con el fin de optimizar las escalas de los tramos.

Otra modificación realizada al cuestionario base (o sección "pétrea") fue la re estructuración de las preguntas sobre las razones que llevaron al hogar a elegir el destino al que finalmente viajaron y si ya habían visitado ese lugar con anterioridad.
Ambas preguntas fueron incorporadas en julio de 2012 con el fin de obtener información más específica y certera sobre los fundamentos que impulsaron al hogar a optar por ese destino y no por cualquier otro.
Así, los hogares deben definir si los atractivos naturales del lugar, la oferta histórica y cultural, la cercanía, los precios, la sugerencia de familiares o amigos que fueron allí antes, la residencia de familiares o amigos o la publicidad audiovisual influyeron en la decisión del destino.
Además, se indaga sobre la eventual evaluación de otro destino y sobre la visita previa de alguno de los miembros del hogar a ese destino.

Finalmente, se reformuló la pregunta sobre Comportamiento Turístico: para aquellos que viajaron en el año anterior, se indaga si viajaron dentro de Argentina y/o al Exterior (en reemplazo de la pregunta sobre si habían viajado por ocio o para visitar familiares -y la razón motivo) dado que esto no aportaba información valiosa.

### **DESCRIPCIÓN DEL FORMULARIO**

En la presente sección, se describe el cuestionario (anexado a El Pliego), que se utilizará para la presente edición de la EVyTH.
Este puede ser dividido en dos grandes secciones: un bloque "pétreo" (cuyo contenido solo esporádicamente sufre alguna alteración menor) y otro bloque conformado por preguntas que cambian en función de relevamientos "ad-hoc" que resultan de interés según el período y la ocasión.
Si bien esta sección es utilizada para indagar sobre la expectativa que los encuestados tienen en relación a la posibilidad de realizar algún viaje en un momento futuro (como los períodos de alta estacionalidad turística), puede ser utilizada, también, para llevar adelante encuestas de opinión u de otra índole[^planeamiento-de-los-aspectos-19] (durante la EVyTH-20 se indago sobre los perjuicios que tuvo la pandemia a causa del virus COVID-19 y sobre futuros viajes pos pandemia).

[^planeamiento-de-los-aspectos-19]: Su característica básica es que es completamente flexible permitiendo realizar relevamientos "ad-hoc" de forma fácil.

#### **CUESTIONARIO BASE (SECCIÓN "PÉTREA")**

Como se indicó anteriormente, la sección del cuestionario que se describe a continuación prácticamente no ha sufrido alteraciones desde el comienzo de la primera edición de la EVyTH en el año 2010[^planeamiento-de-los-aspectos-20] (para su consulta ver sección 6.6).
La idea es minimizar los cambios de contenido a esta parte del cuestionario con el fin de lograr la mayor compatibilidad entre los datos relevados en distintos momentos del tiempo y, de esta forma, generar una serie de tiempo lo más extensa posible.
Esta sección "pétrea" del cuestionario, se compone de 9 Bloques; a saber:

[^planeamiento-de-los-aspectos-20]: Ver sección anterior donde se describen las modificaciones introducidas a esta sección.

1.  Bloque "Característicasdelosmiembrosdelhogar".Estebloqueestásubdivido en tres.

    (i) Al inicio de la encuesta, sólo se indaga por la cantidad de personas que integran el hogar y las iniciales (de forma tal de mantener el anonimato) de cada uno de los miembros del hogar.
    (ii) Al final del cuestionario, luego de indagar por la realización de viajes y visitas y sus características, se indaga por las características de los miembros del hogar, bajo el supuesto de que, con el devenir de la encuesta, el entrevistado gana confianza y se muestra menos renuente a responder estas preguntas. En este mismo sub-bloque se indaga por el comportamiento turístico en el año calendario anterior a la encuesta (año 2020)[^planeamiento-de-los-aspectos-21]; (iii) La indagación por los ingresos totales del hogar, que cierra la encuesta, se incluye como otro sub-bloque también al finalizar el Formulario Base.

2.  Bloque "Segundas Viviendas".
    Se indaga únicamente por las segundas viviendas que el hogar dispuso y utilizó durante el periodo de referencia.

3.  Bloque "Viajes de corta duración a segundas viviendas": 1 a 3 noches (VCDS).

4.  Bloque"Viajesdelargaduraciónasegundasviviendas":4nochesomás(LDSV).

5.  Bloque"Visitasdeundíaasegundasviviendas"(VDSV).

6.  Bloque"ViajesnoreiteradosenArgentina"(VA).

7.  Bloque"Viajesnoreiteradosalexterior"(VE).

8.  Bloque "Viajes a destinos reiterados" (DR).
    Este bloque funciona como "reserva", es decir, no se pregunta directamente al entrevistado si realizaron viajes de este tipo, sino que el encuestador lo completa en caso de detectar la existencia de este tipo de viajes en la indagación de los bloques anteriores (VA y VE).

9.  Bloque"Visitasdeundía".

[^planeamiento-de-los-aspectos-21]: Este aspecto se indaga durante los meses de febrero hasta mayo inclusive.

10.Bloque sobre viaje en períodos turísticos especiales.
Este relevamiento complementario indaga por la posibilidad de que alguno de los miembros del hogar haya realizado viajes en la/s fecha/s especiales durante los meses de referencia (por ejemplo, períodos de temporada de verano/invierno).
Es un bloque del cuestionario base que se "activa" automáticamente cuando, en los meses de referencia, ha habido un fin de semana largo.
En función de ello, se consulta explícitamente si el encuestado ha viajado durante ese momento específico del mes.

11.Comportamiento turístico de las personas.
Finalmente, el formulario también incorpora, solo durante los meses de febrero a mayo, una sección donde se indaga por viajes realizados durante al año anterior a modo de conocer el comportamiento turístico de las personas.
Con la información recabada en esta sección se confecciona el informe sobre Comportamiento Turístico de las Personas (ver sección 3 más adelante).

Sinópticamente, la lógica del Formulario Base puede resumirse a través del Cuadro 5:

**Cuadro 5: Esquematización del Cuestionario utilizado durante la EVyTH**

El cuestionario base contiene su propia terminología para caracterizar a los viajes (en sentido amplio).
Así, por ejemplo, cuando el visitante pernocta al menos una noche en el lugar de destino, se especifica como "viajes" y "viajeros" propiamente dichos.
Cuando la persona no pernocta en el lugar de destino, se hace referencia a "visitas de un día" y "visitantes" o "excursionistas".
Por lo tanto, en función de una serie de variables, se han definido diferentes tipos de viajes.
Estas variables son:

1.  Cantidad de noches en el lugar visitado. Se consideran las noches pasadas en alojamientos del lugar visitado.
2.  Tipos de Alojamiento donde pernoctaron. Se clasifican en dos grupos:

<!-- -->

a.  "Segundas viviendas"
b.  "Otros tipos de alojamientos": aquí se incluyen todos los tipos de alojamiento diferentes a las segundas viviendas (hoteles de todas las categorías, camping, casas de familiares o amigos, viviendas alquiladas por temporadas, etc.).

<!-- -->

3.  UbicacióndelDestinoPrincipal,segúnsea:

<!-- -->

a.  En Argentina (ciudad/localidad).
b.  En otro país.

<!-- -->

4.  Viajes Similares en los últimos 2 meses. De acuerdo a la cantidad de viajes realizados a un mismo destino con características similares (miembros participantes, cantidad de noches, tipo de alojamiento, motivo principal, etc.) los viajes se clasifican en:

<!-- -->

a.  "Reiterados": cuando hayan realizado 3 o más viajes en los últimos 2 meses.
b.  "No reiterados": cuando se hayan realizado uno o dos viajes en los últimos 2 meses.

La información que se solicita depende del tipo de viaje que se trate y se registra en un Bloque específico del Formulario Base.
Esta clasificación responde a la estrategia definida para mejorar la indagación y captación de los distintos viajes que las personas pueden realizar.
En función de las variables mencionadas, llegamos a la siguiente clasificación:

**Cuadro 6: Caracterización de los Viajes a ser Relevados y Ubicación en el Formulario Base**

En la última columna del cuadro precedente se señalan dos situaciones: (a) en ciertos tipos de viajes (CDSV, VDSV, VR, VD), dentro de cada bloque, se indaga por la cantidad de viajes o visitas realizadas a cada lugar visitado y luego se realizan algunas preguntas sobre el último de los viajes o visitas a cada lugar; (b) en otros tipos de viajes (LDSV, VA, VE) se consulta directamente por cada uno de los viajes realizados.
Esto es así porque por la propia definición de los tipos de viaje que componen el primer grupo se trata de viajes muy parecidos entre sí; en cambio, en el segundo grupo, los viajes englobados dentro de un mismo tipo pueden ser totalmente distintos.

Excepto algún caso particular, existe un núcleo de preguntas que no varía según el tipo de viaje realizado por el hogar.
Por ejemplo, se consulta por destino, tipo de alojamiento, actividades, etc.

#### **SECCIÓN "AD-HOC" DEL CUESTIONARIO**

Como fuera mencionado anteriormente, esta sección del cuestionario fue incorporada en la edición de 2013 de la EVyTH y tuvo como función primordial relevar las expectativas de viaje de los hogares argentinos durante fechas especiales dentro de cada mes de relevamiento, así como también, durante los periodos de alta demanda de turismo como el invierno y el verano.
La decisión de incorporar este relevamiento complementario se basó en la importancia de conocer anticipadamente (ex ante) los viajes que los hogares argentinos prevén realizar ante la implementación de una política pública como la incorporación y/o reestructuración de nuevos feriados nacionales por parte del gobierno nacional[^planeamiento-de-los-aspectos-22], así como también para los periodos vacacionales como el periodo invernal y el periodo estival.
Por esta razón, al finalizar el cuestionario "pétreo", se incorpora una sección (o cuestionario "ad-hoc") sobre expectativas de viajes durante los períodos relevantes.

[^planeamiento-de-los-aspectos-22]: De acuerdo con Decreto 245/2011 y la Ley 26.721.

De acuerdo con El Pliego, la edición de la EVyTH (EVyTH-21) prevé el relevamiento de expectativas de viajes para las quincenas de temporada invernal (contemplando las expectativas de viajes que se realicen durante los meses de julio y agosto de 2021) y de verano (considerando las expectativas de viajes que se realizarán entre los meses de diciembre hasta marzo inclusive).

El relevamiento sobre expectativas para medir el caudal turístico y principales características del viaje en fechas especiales, se llevará a cabo durante quince días hábiles anteriores a la fecha de entrega del informe de resultados (siguiendo el Pliego, la entrega debe realizarse diez días antes del inicio de la temporada turística de invierno y verano).
En cada fecha clave, se relevará la cantidad de turistas, el destino (región turística para Argentina y "Exterior" para países extranjero), el motivo, el tipo de alojamiento y la duración del viaje para una muestra de 1.500 casos relevados.
Estas preguntas se realizan al final del bloque de preguntas sobre los miembros del hogar del cuestionario base y antes de la pregunta sobre ingresos del mismo cuestionario.
De esta manera, se mantiene la pregunta de menor respuesta, ingresos del hogar, en el último lugar para así obtener mayores posibilidades de concluir la encuesta en su totalidad.
Para su consulta ver sección 6.7).

### **INCORPORACIONES SUGERIDAS AL FORMULARIO BASE**

A continuación, se listan y comentan en términos generales algunas propuestas concretas que podrían incorporarse en el Formulario Base a lo largo del relevamiento a llevarse a cabo durante 2021.
La implementación eventual de estas propuestas queda sujeta al criterio del personal técnico del Organismo Contratante.

#### **ÍNDICE DE CONFIANZA DEL TURISTA**

Se propone implementar un nuevo módulo de preguntas destinado a la construcción de un Índice de Confianza del Turista de carácter continuo, y cuyos valiosos frutos podrán observarse cuando haya transcurrido al menos un año.
Deberá ser algo simple, que se realizará a todos los entrevistados al finalizar la encuesta base.
A continuación, una primera propuesta que deberá ser evaluada por el personal técnico del Organismo Contratante y testeada a través de una Prueba Piloto:

P1) En los próximos tres meses, ¿alguno de ustedes viajará por vacaciones, ocio, para visitar familiares o por otro motivo?
(no leer opciones, si dice "no sé" repreguntar si cree más probable que viajen o no)

1)  Si (pase a P1C)
2)  No (pase a P2)
3)  No Sabe, aunque es más probable que viajen
4)  No sabe, aunque es más probable que no viajen
5)  No sabe, y no puede decir si es más probable que viajen o no. 9) No Responde (pase a P2)

P2A) En todo el año 2021, ¿cree que ustedes viajarán por turismo más o menos que lo que han viajado en 2020?

1)  Más
2)  Menos
3)  Lo mismo
4)  NO VIAJAN POR TURISMO (pase a P3) 8) No sabe
5)  No responde

P2B) ¿Y considera que en el año 2021 podrán viajar más o menos que lo que viajarán durante este año?

1)  Más
2)  Menos
3)  Lo mismo
4)  No sabe
5)  No responde

#### **INDAGACIÓN SOBRE LOS HOGARES QUE SE INCORPORAN AL TURISMO**

La comparación de los resultados obtenidos en las ediciones anteriores de esta encuesta da cuenta de un incremento en la proporción de personas y hogares que realizan viajes turísticos a partir de 2006.
En este escenario cabría la posibilidad de indagar sobre cuál es la proporción de hogares que están viajando por primera vez.
El abanico de formas metodológicas para mensurar esta cuestión es amplio y complejo a la vez, lo que ameritaría discusiones profundas sobre la forma de implementarlo, así como los tipos de viajes turísticos a considerar (cualquier tipo o sólo los de ocio, por ejemplo).
Por ejemplo, podría preguntarse a los hogares si es la primera vez que visitan ese destino.

#### **MOTIVO CONGRESOS PARA AQUELLOS QUE VIAJAN POR TRABAJO**

Algunas ciudades se caracterizan por su particular atracción como destinos para congresos y convenciones.
El cuestionario actual no permite identificar cuántos de los viajes que son realizados como motivo de trabajo se corresponden con viajes para asistir a congresos/convenciones por trabajo.
Sería posible incorporar una pregunta que saldara esta deuda.

#### **PROFUNDIZACIÓN DE LOS ASPECTOS REFERIDOS A LOS VIAJES AL EXTERIOR DEL PAÍS POR PARTE DE LOS RESIDENTES QUE NO ESTÁN SIENDO CAPTADOS POR LA ETI**

Actualmente, la Encuesta de Turismo Internacional releva los viajes de los residentes al exterior que se realizan desde los principales aeropuertos del país (Ezeiza, Aeroparque y Córdoba) y desde la terminal portuaria de la Ciudad de Buenos Aires.
Por tal motivo, una parte sustancial de los viajes que los residentes realizan hacia países limítrofes por otros medios de locomoción (automóvil y ómnibus, particularmente) no son captados por dicho relevamiento.
Una forma posible de subsanar esta laguna de información sería agregar algunas breves preguntas que permitan conocer las principales características de estos viajes, además de las que se relevan habitualmente para todos los viajes al exterior.
Si bien por razones de fiabilidad estadística los resultados obtenidos para un mes no serán suficientes, la acumulación luego de una serie de ondas (semestral, anual) permitirá contar con una cantidad de información sustancial para realizar análisis exploratorios.

#### **PROPENSIÓN AL TURISMO DE LOS HOGARES**

Podría resultar de interés tener alguna apreciación sobre las actividades turísticas del hogar en un marco temporal que exceda los meses específicos sobre los que se indaga acerca de la realización de viajes y se acerque más a captar la importancia que el turismo tiene para ese hogar.
Por ejemplo, podría indagarse acerca de si habitualmente suelen tomarse vacaciones en la temporada de verano, si viajan en algún o algunos feriados turísticos y si además realizan viajes fuera de estas fechas.
En consonancia con esto, cabría indagar, por ejemplo, con cuanto tiempo de anticipación planean sus vacaciones estivales, y desde cuando comienzan a ahorrar para tal fin.
Este módulo podría relevarse en los meses de temporada baja.

#### **ETAPAS DEL VIAJE**

Una de las preguntas planteadas en el Formulario Base se refiere a cuántos lugares visitaron además del destino principal.
Una posible implementación sería que se indague sobre cuáles fueron las provincias y localidades visitadas, en el caso de que se realicen viajes al exterior cuales fueron los países respectivamente.

#### **UTILIZACIÓN DE INTERNET**

Se sugiere modificar la pregunta actual sobre la utilización de Internet para consultar o contratar información relacionada al viaje.
Se propone indagar si la contratación de alojamiento pago, medio de transporte público y paquete fue por medio de Internet o no.
Y, en caso de no haber adquirido ese tipo de servicios y/o las respuestas resultaran negativas, se realizaría una pregunta genérica sobre el uso de internet, por ejemplo: "¿USTED O ALGUNA DE LAS PERSONAS QUE PARTICIPÓ DEL VIAJE, USARON INTERNET PARA ORGANIZAR EL VIAJE O CONSULTAR INFORMACIÓN SOBRE CÓMO VIAJAR, DÓNDE COMER, QUÉ HACER, EL CLIMA, ETC.?".

*Nota 1*: se podría distinguir entre contratación en línea vía OTA (Booking, Despegar, Plataforma 10, etc.) y gestión/reserva por internet distinto de OTA (por ej., contratar una cabaña por haber visto en la web y en base a eso contactar al dueño directo).

*Nota 2*: Se haría necesario definir si se continúa indagando esto sólo para los viajes por ocio no a segunda vivienda o si se extendería a todos los viajes (incluso, también a las visitas de un día).

#### **PARTE INTERNA DE VIAJES EMISIVOS**

Se sugiere evaluar la factibilidad de incluir pregunta simple que capte la existencia o no de un destino interno en viajes emisivos.
Por ejemplo: "¿SU VIAJE AL EXTERIOR INCLUYÓ AL MENOS UNA NOCHE ALOJADOS EN ALGUNA LOCALIDAD ARGENTINA?".

#### **EVALUACIÓN DE DESTINOS ALTERNATIVOS**

Se propone reemplazar el enunciado actual por una redacción más coloquial, a fines de obtener un mejor nivel de respuesta.
Por ejemplo: "¿DESDE EL INICIO HABÍAN DEFINIDO VIAJAR A ESTE LUGAR, O TAMBIÉN PENSARON EN OTROS LUGARES ANTES DE DECIDIRSE A VISITAR.....?".
Las opciones de respuesta serían: 1-Destino decidido desde el inicio; 2- Pensaron en otros lugares.

#### **DESAGREGACIÓN DEL GASTO DE VIAJES Y VISITAS**

Como propuesta a implementar en el Formulario Base, se puede considerar la desagregación del gasto.
En el cuestionario implementado en la EVyTH-21, una de las preguntas referidas al gasto era la siguiente: "Aproximadamente, ¿Cuánto gastaron en total en el viaje, incluyendo los gatos de todos los miembros del hogar en transporte, alojamiento, comidas, excursiones, etc.?"; se sugiere incorporar preguntas para la apertura del mismo gasto total (que continuaría indagándose, al inicio para que no se vea afectado el nivel de respuesta por las preguntas desglosadas).
A continuación, se detalle el desglose que se sugiere realizar:

1)  Transporte: incluye gastos en servicios de transporte público (micro, ómnibus, tren, avión, etc.) como nafta y peajes. En todos los casos, refiere al transporte entre origen-destino (y, eventualmente, entre etapas del viaje). Esto es primordial pues permite discriminar el gasto en destino.
2)  Alojamiento: en todo tipo de alojamientos por los que se deba pagar (hoteles y similares, camping, viviendas de alquiler temporario, otros pagos).
3)  Resto: Bajo esta variable se reunirían los gastos que no se incluyen en los ítems anteriores, como ser alimentación, excursiones, entradas a espectáculos, regalos y suvenires, etc. Sólo para los viajes y visitas internos.

### **RELEVAMIENTOS AD HOC: INFORMES NO BÁSICOS**

A partir de la reunión de capacitación con el personal técnico del Organismo Contratante realizada con motivo de dar cierre a la EVyTH-17, surge la necesidad de replantear algunos ejes temáticos de los informes "ad hoc", incorporados a la Encuesta durante las pasadas experiencias de la EVyTH.
La lista de nuevas variables definitivas a incorporar en el relevamiento debe estar sujeta a las necesidades que plantee el equipo técnico del Organismo Contratante, sin embargo, a continuación, se enumeran posibles temáticas a incorporar:

1.  Destino Ideal: Se podría incorporar, por ejemplo, en los relevamientos de expectativas de invierno y verano, una pregunta por el destino ideal de los hogares suponiendo que el hogar dispusiera de los recursos necesarios (tiempo, dinero, etc.).
    Se replica experiencia pasada, si bien los resultados no revisten mayor interés (pues no variarán mucho de lo que se conoce), el Organismo Contratante los puede encontrar positivos para su comunicación.

2.  Conocimiento y Deseo de Conocer Destinos Turísticos Estratégicos del País: Mediante la implementación de un módulo ad hoc, dirigido sólo a la persona que responde la encuesta (no a la totalidad de miembros del hogar) podría indagarse acerca del conocimiento o no, y sobre las ganas de visitar por primera vez o de regresar a destinos turísticos estratégicos de Argentina (Cataratas del Iguazú, Bariloche, Quebrada de Humahuaca, Sierras de Córdoba, Glaciar Perito Moreno, por ejemplo).
    La respuesta del entrevistado, para cada lugar, quedaría englobada en alguna de las siguientes categorías: No lo conoce y tiene interés en visitarlo, No lo conoce y no tiene interés en visitarlo, lo conoce y le gustaría visitarlo nuevamente, lo conoce, pero no volvería.
    Al término de un periodo temporal amplio (semestral, por ejemplo) se tendría una muestra lo suficientemente significativa para analizar esta información no sólo para el total de los aglomerados sino también de acuerdo a las regiones y a diferentes características de las personas.
    Por razones referidas a la duración de la entrevista, este módulo podría incorporarse en los meses en que se releva información sobre viajes turísticos realizados en los meses de temporada baja.
    Misma lógica podría seguirse para destinos "estratégicos", como Iberá.

3.  Estudio de los hábitos turísticos de la población: amén de si viajan o no, clasificar a los hogares viajeros según frecuencia, tipos de viaje (uno largo anual, varios cortos, etc.), destinos (cercanos/lejanos; Argentina/Exterior), trayectorias (si siempre viajaron, si lo empezaron a hacer en los últimos años, etc.), etc.

4.  Incorporación "temporal" de preguntas en cuestionario base: esta es otra modalidad de relevamiento ad hoc, y consistiría en profundizar por un determinado tiempo (vinculado a la precisión requerida/tamaño de muestra mínima) sobre algún aspecto del viaje.
    Por ejemplo, un breve módulo sobre la importancia de la gastronomía en viajes internos, profundizar sobre algunas características de los viajes emisivos para aumentar la comprensión sobre todo de los "no ETI", etc.

Por otra parte, algunos informes no periódicos no requieren ser realizados una vez al año (por ejemplo, el informe de Destinos) ya que presentan un gran componente estructural y, al mismo tiempo, realizar este informe con información agregada de al menos 3 años permitirá robustecer los resultados al agregar muestra durante un período más prologando.
Por esto se sugiere realizar algunos cambios:

1.  Comportamiento turístico: Se sugiere incorporar información sobre destino en Argentina/Exterior.

2.  Destinos: Se sugiere realizar este informe con información agregada 2012-2020 (8 años completos) y modificar el nombre a "Eje PFETS".
    Además, se sugiere revisar otras clasificaciones (tipo de atractivo, demográfico, oferta).

## **CONSISTENCIA Y VALIDACIÓN**

Con el objeto de garantizar la calidad de la información se utilizará, tal como se expuso en La Oferta, un proceso de validación y consistencia de los ficheros resultantes de la encuesta para aplicarse previo a cualquier imputación o tratamiento de información faltante.
Dicho proceso se implementará mediante un programa que permita gestionar el proceso de validación y las correspondientes correcciones en los casos de hallar inconsistencias que ha sido diseñado especialmente para la EVyTH (este sistema ya ha sido probado con éxito en ediciones anteriores de la EVyTH --como, por ejemplo, en la EVyTH-11, EVyTH-12, EVyTH- 13, EVyTH-14, EVyTH-15, EVyTH-16, EVyTH-17, EVyTH-18, EVyTH-19 y la EVyTH-20).
En este tipo de procesos, el objetivo es controlar los valores o el campo de variación (rango de valores) de cada variable del cuestionario.
En una primera etapa la validación se realiza exclusivamente para cada uno de los individuos registrados, independientemente de su interrelación con la información relevada en otros individuos del mismo hogar.
Esto significa que esta validación inicial se realiza en forma independiente para cada individuo y para cada variable del cuestionario.
En las preguntas cerradas se controla que los códigos introducidos se encuentren dentro del rango de valores correspondientes a dicha variable.
Por ejemplo, en la variable "NIVEL DE INSTRUCCIÓN", sólo deben presentarse los códigos 01 a 10 y el código 99 para el caso de no respuesta.
Una segunda etapa del proceso de validación y consistencia consiste en la validación cruzada de la información contenida entre variables relevadas en un mismo individuo.
Es decir, se analizan las interrelaciones lógicas entre dos o más preguntas de un mismo individuo.
Por ejemplo, si no responde en la pregunta sobre si trabaja o no, pero luego responde que es "ama de casa", entonces debería corresponder la respuesta "No" a la pregunta sobre si trabaja.

El proceso de validación también implica el manejo de las encuestas parcialmente completas.
Se propone implementar un criterio para determinar cuáles encuestas no pueden ser utilizadas para extraer información y cuáles si, de forma tal de minimizar la pérdida de datos.
Se considera una encuesta válida cuando el respondente haya contestado todas las preguntas referidas al comportamiento turístico del hogar dentro del periodo de referencia correspondiente y, al menos, haya respondido sobre las características básicas del jefe (sexo, edad, nivel educativo).
Si bien la gran mayoría de los entrevistados responden hasta el final de la encuesta (y, por ende, se cuenta con las características de cada una de las personas que integran el hogar), en algunas ocasiones el respondente se niega a suministrar información personal.
Como se mencionó, en estos casos el criterio para dar por válida una encuesta es que al menos se haya obtenido la información básica sobre el jefe.
En base a la información recolectada hasta allí (cantidad de integrantes, características del jefe, observaciones del encuestador sobre el sexo y/o la edad de las personas restantes - información que suele surgir durante el desarrollo de la entrevista), el Jefe de Estadística procede a imputar las características básicas de las personas del hogar faltantes.
Por último, existirá un proceso de validación "ex -- post".
Este mecanismo consiste en estudiar cada una de las variables discriminadas en función de distintos cortes (etarios, regionales, etc.) con el fin de analizar respuestas que se ubiquen fuera de los rangos definidos como "normales".

## **PROCEDIMIENTO DE IMPUTACIÓN**

Una vez finalizada la etapa de validación y consistencia de la información comienzan las tareas de imputación de la falta de respuesta en las variables de cada base de datos.
En la sección a continuación se realiza una breve descripción del proceso de imputación de las principales variables relevadas por la EVyTH (ingreso total del hogar y gasto del viaje); mientras que en el apartado 6.2.3 se realiza una descripción más pormenorizada.
Desde el punto de vista conceptual, el método de imputación que se utilizará, al sustituir valores perdidos, requiere que la imputación no modifique las características de la variable en estudio.
Por este motivo es recomendable demostrar, luego de la imputación, que no se han generado cambios relevantes en la distribución de la variable imputada.
En una primera instancia se procede a estudiar y evaluar la imputación de las variables "Ingreso Total del Hogar" y "Gasto en Viajes", sin embargo, lo aplicado en esta situación será empleado en otras variables de interés (por ejemplo, edad, sexo y situación laboral).
Para el caso de la variable Ingreso Total del Hogar, considerando que se trata de una variable categórica ordinal, para su imputación se utilizará un modelo de Regresión Logística Politómica con Variable Respuesta Ordinal.
Este procedimiento se lleva a cabo en SAS®[^planeamiento-de-los-aspectos-23].

[^planeamiento-de-los-aspectos-23]: La metodología de imputación que se propone en la sección tiene la ventaja de que ya fue testeada con las bases de la EVyTH-06, de la Prueba Piloto de la EVyTH-11, la EVyTH-12, la EVyTH-13 la EVyTH-14, la EVyTH-15, la EVyTH-16, la EVyTH- 17, EVyTH-18, EVyTH-19 y la EVyTH-20.

Para el caso de la imputación de la variable "Gasto del Viaje", al ser una variable continua (no está categorizada), la metodología a implementar para su imputación sigue un modelo de regresión en dos etapas puesto que debe contemplarse que la variable ingreso es una variable con distribución marcadamente sesgada (por lo que una técnica que asuma una distribución Normal no debería ser adecuada sin una previa transformación que asegure dicho supuesto).
Esta metodología busca, en la primera etapa, "colocar" el valor del gasto faltante en una categoría de gasto, en función de los valores observados en las variables explicativas mientras que, en la segunda etapa, se selecciona un valor de esa categoría para "asignar" al registro.
Por otra parte, entre las variables explicativas que se tomaron en cuenta (ver más detalles en sección 6.2.3) para su imputación se encuentran: distancia recorrida, cantidad de noches, cantidad de miembros del hogar, tipo de alojamiento, medio de transporte utilizado, motivo del viaje, tiempo de organización del viaje, mes en que se realizó el viaje, entre otras.

## **PROCESO DE CALIBRACIÓN**

Una etapa crítica en toda encuesta por muestreo es la expansión de la información.
Una selección adecuada, y el posterior desarrollo, de una metodología para ponderar los datos muestrales es importante, ya que debe atender simultáneamente varias necesidades.
Las distintas temáticas estudiadas, y la necesidad de lograr estimaciones adecuadas para cada una de ellas, obliga a que ésta sea lo más eficiente posible, en términos de precisión, cuidando no privilegiar a algunas en perjuicio de otras.
Al mismo tiempo, su implementación debe ser simple, flexible y económica en tiempos de ejecución y cálculo.

Uno de los problemas más comunes en las encuestas complejas de gran envergadura es que una vez desarrollado el trabajo de campo existen algunos subgrupos de la población objetivos sub o sobre-representados.

Esta dificultad lleva a que los sesgos puedan ser importantes, impidiendo una interpretación correcta de las estimaciones o imposibilitando la comparación de los resultados con fuentes alternativas.

Para corregir esto, en la práctica es habitual corregir los pesos o factores de expansión iniciales (las inversas de las probabilidades de inclusión) con la ayuda de información auxiliar.
El hecho de contar con dicha información auxiliar en la etapa de estimación permite el empleo de estimadores que la involucran.
Dentro de este tipo de estimadores están los que se obtienen a través de los métodos de calibración.
Éstos, en su forma más general, tienen como objetivo crear nuevos pesos que resultan de modificar o calibrar las ponderaciones iniciales por diseño.

El empleo adecuado de la técnica de calibración permite:

-   Reducir el error cuadrático medio de las estimaciones.

-   Corregir posibles sesgos en la etapa de selección.

-   Dar una solución al problema de "no-respuesta".

-   Lograr, a partir de las restricciones impuestas, una deseable consistencia, o concordancia, entre los totales conocidos y los obtenidos a través de la muestra, de las variables auxiliares.

La calibración consiste básicamente en la resolución de un problema de minimización numérica.
Dicho problema queda planteado con la elección de una distancia, entre los nuevos ponderadores y los originales, y la utilización de un conjunto de restricciones impuestas sobre las variables auxiliares que intervienen en el ajuste.

**(Nota para mi yo del futuro, acá van una seria de fórmulas de la Pag 37 en adelante)** Sea una función G que cumple con ciertas propiedades, y donde $G(wk/dk)$ mide la distancia existente entre el peso original dk y el nuevo peso $wk$, y donde $ dk G(wk / dk )$ es la medida de la distancia para la muestra completa s.
El problema de optimización es minimizar $sdkG(wk /dk)'swkxk Uxk$ donde el vector es el multiplicador de Lagrange.

Diferenciando con respecto a wk, se obtiene g(wk / dk )  x 'k λ  0 , donde g(x)  dG(x) / dx .
Luego, resolviendo para wk se obtiene wk  dk F(x 'k λ) , donde F(u)  g1(u) representa la función inversa de g(.).
Para calcular los nuevos pesos, se determina el valor de λ resolviendo las ecuaciones de calibración dkF(x'k λ)xk  xk sU (1.1) donde el vector λ constituye la única incógnita.
El sistema puede ser resuelto por métodos numéricos.
Una solución general está constituida por el método de Newton.
(λ)d F(x' λ)1x kkk ˆ Sea s s , podemos escribir (1.1) como s(λ)  tx  tx , donde ˆ tx  U xk , y tx  s dkxk es el estimador de Horvitz-Thompson.
Sea 's(λ)  s(λ)/λ .
Luego comenzamos el proceso iterativo fijando λ0  0 , y obteniendo los valores λv , correspondientes a cada paso v (v=1,2,...) del proceso iterativo, mediante 1ˆ  λv1 λv 's(λv) t t (λ) x x s v (1.2) Teniendoencuentaques(0)0;'s(0)Ts sdkxkx'k ,laprimeriteraciónbrindael ˆ 1 s x x v valor λ  T1(t  t ) , mientras que las iteraciones sucesivas brindan valores λ de acuerdo a la fórmula (1.2), hasta que el criterio de convergencia es cumplido.
En forma resumida, el proceso de calibración consta de los siguientes pasos:

1.  Dados los datos (yk , xk ) observados para los elementos de la muestra, o sea, k  s , y dada una función de distancia G (y la correspondiente función F), resolver el sistema (1.1) para λ.
2.  Una vez determinado λ, calcular los pesos calibrados wk  dk F(x 'k λ) y el estimador de calibración.

Con respecto a las funciones de distancias, en la literatura se mencionan siete funciones distintas de distancia G, y su correspondiente F.
Para el presente trabajo se utiliza y adapta la macro CALMAR[^planeamiento-de-los-aspectos-24], escrita en lenguaje SAS por Sautory (1991), la cual calcula los pesos calibrados cuando la información auxiliar de una encuesta consiste de totales marginales conocidos dispuestos en una tabla de frecuencias de dimensiones arbitrarias.
La macro mencionada trabaja con cuatro funciones G, de las cuales para la EVyTH se trabajará sólo con tres.
A continuación, se brinda una pequeña descripción de cada una de ellas.

[^planeamiento-de-los-aspectos-24]: El algoritmo del Calmar a utilizar durante la calibración puede ser consultado en: <http://www.restore.ac.uk/PEAS/saspackage.php>

1.  Método Lineal: G(x)=(1/2)(x-1)2; x; F(u)=1+u

2.  Método multiplicativo (o método ranking):

G(x)  x log x  x  1; iii.
Método logit: Fijar dos constantes L y U, tal que L\<1\<U, y sea

x  0;F(u)  exp(u)  0\
A  (U  L) / (1  L)(U  1) .
Luego

G(x) 1 (x  L)log x  L  (U  x)log U  x  A 1L U1



si L\<x\<U, y G(x)   en otro caso.
La función F correspondiente es: F(u) L(U1)U(1L)exp(Au)

U 1(1 L)exp(Au) que toma valores entre L y U

La función logit descripta en el punto iii), constituye una función inusual que surge del deseo de restringir el rango de los nuevos pesos wk para evitar los pesos extremos, los cuales pueden ser eliminados a través de una apropiada elección de L y U.

Para el proceso de calibración de la EVyTH se intentará, no siempre con éxito (de acuerdo con nuestra experiencia en las ediciones de la EVyTH anteriores), utilizar el método i, dado que el proceso iterativo solamente involucra un paso.
La dificultad que posee este método es que, en muchos casos y debido a la estructura interna de la muestra con respecto a las variables de calibración, brinda pesos negativos los cuales obviamente no tienen sentido dentro del muestreo.
Es por ello que para aquellas Regiones donde se encuentran estas dificultades, se adoptará por aplicar el método ii), el cual posee la ventaja de evitar los pesos negativos.

El método iii se aplica en aquellas Regiones donde los nuevos pesos calculados por el método i o ii resulten extremos.
Se intenta, en la mayoría de las Regiones, que los pesos resultantes

cumplan con la siguiente condición: 0.7  wk dk  1.5 , necesitando en algunas Regiones ampliar dichos márgenes.

Se propone efectuar la calibración en forma independiente en cada Región dado que las muestras son independientes y además se pretende brindar estimaciones de cada una de ellas.

Con respecto a la información auxiliar a emplear para la calibración y el ajuste de las estructuras internas de la muestra, se pretende recurrir a proyecciones de población en base al INDEC.
Se propone, entonces, tener en cuenta los siguientes totales a nivel de cada una de las siete Regiones:

-   Total de personas por sexo.

-   Total de personas por grupos de edad.

-   Total de personas por nivel educativo.

-   Total de viviendas.

Los grupos de edad están compuestos de la siguiente manera:

-   0--17años,

-   18 -- 34 años,

-   35--54años y

-   mayores de 55 años.

Nivel Educativo está conformado por cuatro grupos siendo los mismos:

-   "Sin Instrucción/Hasta Primario Incompleto",

-   "Primario Completo/Secundario Incompleto",

-   "Secundario Completo/Terciario Incompleto/Universitario Incompleto" y

-   "Terciario Completo/Universitario Completo/Posgrado/Maestría/Docto

Importa aclarar que los Totales de Población y Viviendas a utilizar en la calibración se obtienen de Proyecciones elaboradas por INDEC, las cuales actualizarán a medida que se disponga de la información del Censo Nacional de Población, Hogares y Viviendas desarrollado en el 2010.

Por otra parte, para cada uno de los meses de relevamiento, se realizarán 2 calibraciones.
Una calibración, inmediatamente al final del relevamiento con el objetivo de dar el anticipo nacional de las principales estimaciones de interés correspondiente a los viajes realizados durante el mes anterior al de relevamiento.
La segunda calibración se realizará al final del bimestre donde se dan todas las estimaciones definitivas a nivel regional para el mes que haya duplicado la muestra (5.200 encuestas).
Es decir, si el mes de relevamiento fuera enero, por ejemplo, se consulta por los viajes realizados (que finalizaron) en el mes de diciembre y noviembre (1 y 2 meses atrás del mes de relevamiento).
Al final del relevamiento de ese mes (enero) se brinda un anticipo nacional para el mes de diciembre con un tamaño de muestra de 2.600 hogares.
Luego, durante el próximo mes de relevamiento (febrero), el período de referencia serán los meses de diciembre y enero, por lo que, al finalizar, producto del solapamiento descripto anteriormente (ver sección 2.6.2), se habrán relevado 5.200 hogares para el mes de diciembre (2.600 durante el relevamiento de enero y 2.600 casos durante el relevamiento de febrero).
Por lo tanto, al finalizar el relevamiento de febrero se brindará una estimación definitiva con nivel de desagregación geográfica regional para el mes de diciembre y un anticipo nacional (con 2.600 casos) para el período de referencia de enero.

Es preciso aclarar que tanto la calibración correspondiente al anticipo (con representatividad nacional) y definitiva (con desagregación por región) de cada uno de los meses, se realizará en forma independiente en cada una de las Regiones.
Por lo tanto, la calibración del anticipo se llevará a cabo en cada una de las regiones, brindándose resultados nacionales, y luego, al mes siguiente, se volverá a realizar una calibración en cada región con el total de la muestra definitiva (para lo que no se consideran los ponderadores estimados durante el anticipo).

Para salvar posibles inconsistencias en los cuadros a publicar, los pesos calibrados son tratados por un algoritmo de redondeo para eliminar la componente decimal con los que salen del proceso iterativo sin destruir las concordancias alcanzadas.

## **COEFICIENTE DE VARIACIÓN**

### **INTRODUCCIÓN**

La metodología de la EVyTH-13 incorporó el cálculo de estadísticos (o indicadores) con la finalidad de brindarle al usuario de los datos una medida del grado de precisión de las estimaciones calculadas para cada uno de los informes de resultados.
Esto es especialmente relevante con el fin de brindarle al lector noción sobre cuán preciso es el estimador que irá a utilizar (o citar) de forma tal que este pueda medir los "riesgos" que ello implique.

Se propone para la presente edición de la EVyTH, la EVyTH-2021, continuar con la misma metodología.
En el apartado que sigue a continuación se describe la lógica utilizada para el cálculo de esta medida de precisión y se listan las estimaciones para las cuales se calcularán esta medida.

### **CÁLCULO DEL COEFICIENTE DE VARIACIÓN**

Los estudios por muestreo a gran escala con objetivos múltiples se enfrentan generalmente con el problema de proveer a los usuarios de datos de diversa formación en estadística, una medida de calidad de los datos.
Dentro de este contexto es deseable presentar indicadores de calidad o bien acercar a los usuarios información o técnicas para que ellos los calculen de una manera "amigable", sin la complejidad siempre presente del cálculo del error muestral.

Desde la perspectiva del diseño muestral y considerando la metodología descripta anteriormente, a la EVyTH se la podría encuadrar dentro de los diseños estratificados con selección sistemática dentro de cada uno de los estratos (ocho estratos en total siendo estos las Regiones del Ministerio de Turismo, Capital Federal, Partidos Gran Buenos Aires, Resto Pcia. Buenos Aires, Córdoba, Litoral, Norte, Cuyo, Patagonia).
Si bien el método de selección sistemática es recomendable y eficiente para muestras telefónicas, su uso implica que no exista estimadores no sesgados de varianza.
Para sortear esta dificultad a la hora del cálculo de los errores muestrales se propone plantear el supuesto de que la población está en "orden aleatoria".
Bajo este supuesto se pueden utilizar los estimadores de un muestreo estratificado con selección simple al azar.
Con esto se resuelve el problema de cómo estimar los desvíos estándares[^planeamiento-de-los-aspectos-25] de cada estimador.

[^planeamiento-de-los-aspectos-25]: La fórmula del estimador del desvío estándar cambia según el estimador que se utilice y el diseño muestral aplicado.
    Para el caso del diseño aquí propuesto, el desvío estándar para el estimador de una proporción es: DE(pˆ)  W2 h h (1 f ) donde Wpˆ h es el peso relativo del estrato h, h es el estimador de la proporción en el estrato h, nh es el tamaño de muestra en el estrato h, (1 fh )es el factor de corrección finita en el estrato h.
    (hacer \*formula\*)

También al error muestral se lo puede presentar en forma relativa, a partir del Coeficiente de Variación convenientemente expresado en porcentaje.
Se define al coeficiente de variación de un estimador como el cociente entre el desvío estándar del estimador y el estimador propiamente dicho; o sea

**(hacer formula)** CV()  ˆ o en su defecto multiplicado por 100 para expresarlo en porcentaje Bajo esta forma es mucho más fácil interpretar el error de muestreo que empleando al desvío estándar propiamente dicho, como se lo presentó anteriormente.
Bajo este "termómetro" existe una escala que al menos se sostiene en la práctica para marcar una buena o mala estimación.
Es así que está aceptado en la comunidad estadística que valores superiores al 15% del CV comienzan a señalar un deterioro en la precisión, aunque existen situaciones donde valores aún cercanos a 20% se lo puede considerar con una precisión adecuada dependiendo de la variable bajo estudio y de las necesidades prácticas del usuario de los datos.
En el caso particular de la EVyTH, los informes presentaron el cálculo de los CV para cada estimador relevante (según el informe que se trate), aclarándose para aquellos que presenten un CV superior al 30% que "el resultado debe considerase a título indicativo puesto que la estimación no presenta el mínimo de precisión preestablecido".

En general ninguna estimación coincide exactamente con el valor del parámetro, salvo casualidades de por medio o bien si se tiene características muy especiales de la población.
Por lo tanto, existe una alternativa que pone en evidencia la incertidumbre con la cual uno debe manejarse.En lugar de decir, por ejemplo, que a  lo estimamos por ˆ , se puede plantear que estimamos  a través del intervalo c a c con cierta probabilidad.
**formulas pag 42**

Este es un intervalo alrededor del parámetro, usualmente se lo abrevia ˆc, con "c" conocido como el margen de error para la estimación y lo calcula el estadístico a partir de la muestra extraída.
De esta forma se puede hablar de un estimador por intervalo del parámetro.
Desde el punto de vista conceptual, en ocasiones se prefiere emplear este tipo de estimador que al estimador puntual tratado hasta aquí.
Esta segunda alternativa permite una respuesta prudente: uno no se arriesga a proponer un valor puntual bien particular sino un rango de valores posibles.
Es por esto que las estimaciones frecuentemente también se las presentan en términos de lo que se denomina un intervalo de confianza, para expresar la precisión de manera significativa.

Un intervalo de confianza constituye una medida del nivel de confianza de que el verdadero valor para la población quede dentro de ese rango específico de valores.

Por ejemplo, para construir un intervalo de confianza con un nivel del 90% se lo construye empleando una constante fijada por el nivel de riesgo que decide aceptar el estadístico y una aproximación del desvío estándar del estimador en cuestión.
**formula**  1.64DE()

No se está limitado a elegir un nivel de confianza del 90%, lo puede hacer del 95%, 75%, 50% u otro, en cuyos casos en la práctica sólo hay que modificar la constante que multiplica al desvío.

A partir de esta explicación, además de los CV, en los distintos informes producidos a partir del relevamiento de la EVyTH, se calcularán intervalos de confianza puesto que facilitan la comprensión acerca del grado de precisión de los distintos estimadores calculados para aquellos lectores no instruidos en el tema.

El Cuadro a continuación (Cuadro 7) destalla los Coeficientes de Variación que serán calculados según cada informe producido en el marco de la EVyTH-2021.

**Cuadro 7: Coeficientes de Variación calculados según cada Informe de la EVyTH** pag 43

A los efectos de que el lector de este informe metodológico pueda comprender fácilmente la forma en que se implementará la metodología descripta anteriormente, se brindan a continuación algunos ejemplos de estimaciones de CV (tal como se ha presentado en los informes mensuales de la EVyTH-13).

**Cuadro 8. Análisis de margen de error para informes de adelanto y final. Resultados básicos para agosto 2013** pag 44

**Cuadro 9. Análisis de margen de error para informes de adelanto y final. Visitantes (intervalo de confianza al 90%). Resultados para agosto 2013.** pag 45

## *ORGANIZACIÓN Y EQUIPOS DE TRABAJO*

### *EQUIPOS DE TRABAJO*

A partir de la experiencia desarrollada por MacroConsulting durante las diferentes ediciones de la EVyTH, se cuenta con una precisa estimación de la dimensión de los equipos que deben ser abocados a las diferentes tareas de forma tal de ganar la máxima eficiencia posible y, así, minimizar los costos del operativo.
Sobre la base de esta experiencia, se propone conformar el siguiente equipo para llevar los trabajos para desarrollar la EVyTH-2021 (ver Cuadro 10 a continuación):

**Cuadro 10: Estructura organizativa del equipo** pag 46

A continuación, se brinda las principales cualidades de cada uno de los miembros de este equipo para brindar una representación del grado de experiencia exigido a cada puesto:

1)  Coordinador General. Juan Pablo Tarelli es Licenciado en Economía y Abogado (ambos títulos cursados en la Universidad de Buenos Aires). Posee amplia experiencia en trabajos de consultoría económica, relevamientos y estadísticas en el sector de turismo. El resumen de la experiencia relevante para este trabajo es el siguiente:

<!-- -->

a)  Ha sido coordinador general del Observatorio de Precios Turísticos

b)  Ha sido Coordinador General de la Prueba Piloto para la Encuesta de Turismo Doméstico en Hogares Residentes (prueba piloto de la EVyTH Estival 2011).

c)  Ha sido Coordinador General de la Encuesta de Turismo Doméstico en Hogares Residentes - Período Estival 2011.\

d)  Ha sido Coordinador General de la Encuesta de Turismo Doméstico en Hogares Residentes - Período Estival 2011.

e)  Ha sido Coordinador General de la Encuesta de Viajes y Turismo de los Hogares -- año 2012.

f)  Ha sido Coordinador General de la Encuesta de Viajes y Turismo de los Hogares -- año 2013.

g)  Ha sido Coordinador General de la Encuesta de Viajes y Turismo de los Hogares -- año 2014.

h)  Ha sido Coordinador General de la Encuesta de Viajes y Turismo de los Hogares -- año 2015.

i)  Ha sido Coordinador General de la Encuesta de Viajes y Turismo de los Hogares -- año 2016.

j)  Ha sido Coordinador General de la Encuesta de Viajes y Turismo de los Hogares -- año 2017.

k)  Ha sido Coordinador General de la Encuesta de Viajes y Turismo de los Hogares -- año 2018.

l)  Ha sido Coordinador General de la Encuesta de Viajes y Turismo de los Hogares -- año 2019.

m)  Ha sido Coordinador General de la Encuesta de Viajes y Turismo de los Hogares -- año 2020.

n)  Ha coordinado el equipo para la confección de índices de precios hoteleros obtenidos a partir de los datos obtenidos en la EOH.

<!-- -->

2)  **Jefe de Metodología** Diego Born es licenciado en Sociología por la Universidad de Buenos Aires (UBA) (2005) y Magister en Ciencias Sociales con orientación en Educación por la FLACSO (2010), candidato a Doctor en Ciencias Sociales por la UBA.
    Actualmente se desempeña como consultor en la Dirección de Información y Estadística de la Dirección General de Cultura y Educación de la Provincia de Buenos Aires, donde coordina las tareas de análisis de la información y la implementación de operativos especiales.
    Integra equipos de investigación sobre temáticas sociales y educativas en la Universidad Pedagógica de la Provincia de Buenos Aires (UNIPE) y en la Facultad de Ciencias Sociales de la UBA, donde también es docente.
    Formó parte del equipo de metodología y análisis de la Dirección de Gastos e Ingresos de los Hogares del Instituto Nacional de Estadísticas y Censos (INDEC) (2004-2008).
    Entre 2006 y 2008 se desempeñó en dicha institución como coordinador metodológico de la Encuesta de Viajes y Turismo a Hogares (EVyTH-06).
    Durante el año 2011, fue Jefe de Metodología de la Prueba Piloto de la Encuesta de Turismo Doméstico en Hogares Residentes (prueba piloto de la EVyTH) y luego de la Encuesta de Turismo Doméstico en Hogares Residentes - Período Estival 2011, estando a cargo de la misma función en las ediciones 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019 y 2020 de dicha encuesta (relevamientos para realizados para el ORGANISMO CONTRATANTE).
    En todos los casos, sus tareas han sido la elaboración de cuestionarios y materiales de capacitación, el seguimiento del trabajo de campo, la implementación relevamientos ad-hoc y de modificaciones metodológicas, el análisis de consistencia y el procesamiento de la información recabada y la redacción de los informes de resultados.
    Se ha desempeñado como asesor en metodología para la realización de encuestas de opinión pública (sobre cuestiones educativas y referidas a la coyuntura sociopolítica) en la Unidad Ejecutora Provincial de la Dirección General de Cultura y Educación de la Provincia de Buenos Aires.

3)  **Jefe de Estadísticas** Sergio Passamonti es licenciado en Estadísticas y posee amplia experiencia en diseño de muestras tanto para organismos públicos como empresas privadas.
    Ha participado activamente dentro de la Dirección de Metodología Estadística del INDEC durante la EVyTH 06 y otros relevamientos llevados conjuntamente entre el INDEC y la SECTUR.
    Ejerció como jefe de estadística en la Prueba Piloto, en la EVyTH-11, en la EVyTH-12, en la EVyTH-13, en la EVyTH-14, en la EVyTH-15, en la EVyTH-16, en la EVyTH-17, en la EVyTH18.
    en la EVyTH-19 y en la EVyTH-20.
    Es también consultor del Ministerio de Educación de la Ciudad Autónoma de Buenos Aires.
    En el ámbito privado brinda asesoramiento a las empresas Petrobrás Energía y Carboclor en las distintas encuestas por muestreo que llevan adelante.

4)  **Jefe de Campo** Gonzalo Gustavo Fahey es egresado en Tecnología en Diagnóstico por Imágenes de la Universidad del Salvador.
    Cuenta con una amplia experiencia como encuestador.
    En particular, se ha desempeñado como encuestador desde la EVyTH-12 hasta la EVyTH-17.
    Fue ascendido a Jefe de Campo en la EVyTH-17.

5)  **Jefe de Informática y Comunicaciones** Ignacio Hanesman se desempeña como consultor full-time en MacroConsulting S.A. Se ha recibido de Licenciado en Economía en la Facultad de Ciencias Económicas de la Universidad de Buenos Aires en julio de 2004 y actualmente cursa maestría en Políticas Públicas en la Universidad Torcuato Di Tella.
    Su especialidad dentro de la consultora es la confección de modelos de simulación tarifaria, la realización y el análisis de bases de datos relacionales y multidimensionales y el diseño de plataformas web.
    Experto en sistemas de información para uso de relevamientos on-line y procesamiento de grandes volúmenes de datos.

6)  **Jefe de Coordinación Técnica y Administrativa** Pablo Tanous estudió periodismo y actualmente está cursando la carrera de historia.
    Cuenta con experiencia en relevamiento y encuestas de turismo.
    Se ha desempeñado, primero, como encuestador y luego como supervisor de encuestadores durante diferentes ediciones de la EVyTH.
    Desde la edición de 2019 de la EVyTH es jefe de coordinación técnica y administrativo además de participar en la elaboración de los informes de resultados.
    Precisamente, durante este relevamiento, se desempeña, además, como parte del equipo metodológico en la realización de informes y en la creación de bases de datos de estadísticas de turismo

7)  **Supervisora** Maia Franco es estudiante de Profesorado de Inglés e inglés técnico.
    Cuenta con una amplia experiencia como encuestadora y supervisora.
    En particular, se ha desempeñado como encuestadora durante la EVyTH-13 y EVyTH-14 para ser ascendida a supervisora durante la EVyTH-15, EVyTH-16, EVyTH-17, EVyTH-18, EVyTH- 19 y la EVyTH-20.

8)  **Encuestadores** MacroConsulting cuenta con una valiosa experiencia a partir de la realización de la Prueba Piloto.
    Sus encuestadores ya han adquirido experiencia en el relevamiento de datos para Cuestionario (han relevado durante la EVyTH-11, en la EVyTH-12, la EVyTH-13, la EVyTH-14, la EVyTH-15, la EVyTH-16, la EVyTH-17, la EVyTH-18. la EVyTH-19 y en la EVyTH-20).
    Todos los encuestadores son instruidos (ver Manual del Encuestador y Cuadernillo de ejercicios) al comenzar, así como también durante el relevamiento.

9)  **Mantenimiento de IT** Damián Martín es graduado de la Escuela de Educación Técnica y posee amplios conocimientos en lo concerniente al mantenimiento de software y hardware de PC's para la realización de encuestas telefónicas.

A continuación, en los siguientes cuadros (ver Cuadro 11 y Cuadro 12), se expone un diagrama de tareas que realizará cada equipo, destacándose las tareas durante el relevamiento (en el Cuadro sería el momento "t") y una vez finalizado éste (a partir del momento "t+1", en adelante).
A grandes rasgos, durante la Etapa de Campo, las tareas desarrolladas son las siguientes:

1)  El Equipo de Encuestadores realiza el relevamiento de las encuestas (en cada mes se obtiene como mínimo una muestra de 2.600 encuestas).
2)  Mientras se realiza el relevamiento, el jefe y Supervisor de Campo son quienes controlan la calidad del proceso.
3)  Una vez finalizada esta etapa, el Jefe de Campo procesa la base exportada del Lime Survey, con el fin de generar las variables relevantes para la construcción de las 5 sub- bases. Además de ello, durante la etapa de relevamiento, se realizan controles de calidad en tiempo real y capacitaciones a los encuestadores.
4)  El Equipo Informático, durante este proceso, es quien se encarga del soporte técnico, y el procesamiento y mantenimiento de las bases.

En general, durante la Etapa de Resultados, las tareas llevadas a cabo son las siguientes: 1) Una vez procesadas las bases,el Equipo Metodológico selecciona los hogares válidos en función de la información disponible del jefe del hogar (datos necesarios: sexo, edad y nivel educativo).
2) El Equipo Metodológico se encarga de la consistencia y validación de la base de personas, base de viajes y base de visitantes.
3) Equipo Estadístico genera los factores de expansión.
4) Luego del procesamiento de las bases por parte del Equipo Metodológico (base de personas, viajes y hogares), el Equipo Estadístico se encarga de realizar la imputación del gasto del viaje e ingreso del hogar.
5) Una vez finalizada la validación y consistencia, por un lado,y la generación de factores de expansión y la imputación, por el otro, el Equipo Metodológico realiza el procesamiento de las 5 sub-bases finales a ser utilizadas por el usuario final.
6) El Coordinador General confecciona los informes.
7) El Equipo Metodológico carga los informes al Sistema de Consultas.

**Cuadro 11: Diagrama de Tareas a Confeccionar** PAG 50

**Cuadro 12: Resumen de Tareas y Actividades a desarrollar a lo largo de la EVyTH**

Las tareas del Jefe de Campo fueron implementadas a modo de mejorar cualitativamente el relevamiento de datos.
En esencia su rol es ser el nexo entre el equipo de trabajo del campo y el equipo metodológico.
El objetivo es garantizar la calidad de la información recabada.
Para ello, supervisa, por ejemplo, en tiempo real a los encuestadores (tanto a los remotos como a los "in-situ", organiza cursos regulares de capacitación, participa activamente en la realización del informe de campo mensual (ver más adelante una descripción sucinta sobre este informe), participa de la instrucción de nuevos encuestadores, mensualmente les brinda a los encuestadores detalle de aquellos aspectos que deben mejorar; etc.

Las tareas de la Supervisora de Campo incluyen la asistencia permanente a los encuestadores en cuestiones conceptuales y técnicas, los controles administrativos y la supervisión de la información recabada.
Además, su tarea consiste en realizar un seguimiento diario de la evolución de la muestra de forma tal de garantizar que todas las regiones (localidades censales) contenidas en la muestra sean relevadas según el tamaño pautado y de manera equilibrada durante toda la onda, especialmente durante los días de relevamiento de expectativas de viaje.

Para facilitar el procedimiento anterior, para los casos de las regiones de CABA y Provincia de Buenos Aires, se subdivide (siguiendo la experiencia recabada) la muestra en subregiones (en CABA, norte, centro y sur respetando la situación socioeconómica y para el caso de la Provincia de Buenos Aires, en 6 subregiones según sea conurbano norte, sur, y oeste).

Con cada comienzo de onda la Supervisora realiza el seguimiento de la cantidad de hogares encuestados de forma tal de garantizar que se encuesten el número de hogares necesarios por subregión y a medida que avanza la onda y logra dicho número, pasa al interior de la subregión con el mismo objetivo hasta garantizar que se han encuestado la cantidad de hogares para la localidad (en el caso de CABA[^planeamiento-de-los-aspectos-26] son los barrios y en el caso de la Provincia de Buenos Aires, son las localidades censales).

[^planeamiento-de-los-aspectos-26]: La región CABA está dividida en 15 comunas.
    Trabajando con la mediana del ingreso per cápita se consideran 3 zonas:

    -   Zona Norte: Compuesta por las comunas 2 (Recoleta), 14 (Palermo) y 13 (Belgrano, Núñez, Colegiales).

    -   Zona Centro: Compuesta por las comunas 1 (Retiro, San Nicolas, Puerto Madero, Monserrat, San Telmo, Constitución), 3 (Balvanera, San Cristóbal), 5 (Almagro, Boedo), 6 (Caballito), 11 (Villa Devoto, Villa del Parque, Villa Santa Rita, Villa Gral. Mitre), 12 (Saavedra, Coghlan, Villa Urquiza, Villa Pueyrredón) y 15 (Villa Crespo, Chacarita, Villa Ortuzar, Parque Chas, Agronomía y Paternal)

    -   Zona Sur: Compuesta por las comunas 4 (La Boca, Barracas, Nueva Pompeya, Parque Patricios), 7 (Flores, Parque Chacabuco), 8 (Villa Soldati, Villa Lugano, Villa Riachuelo), 9 (Mataderos, Parque Avellaneda, Liniers) y 10 (Versalles, Villa Real, Monte Castro, Villa Luro, Vélez Sarsfield y Villa Luro).

Se planifica llevar adelante el relevamiento de campo con un equipo estable de 10 encuestadores que encuestarán durante 4 horas diarias.
Además, de resultar necesario, se podrán incorporar encuestadores externos (o remotos) que trabajarán por objetivos semanales de modo de saldar los requisitos en términos de cantidad de encuestas necesarias[^planeamiento-de-los-aspectos-27].
Estos encuestadores "remotos" relevarán con el mismo sistema informático y ateniéndose a los mismos controles por parte del equipo de supervisión, pero fuera de las instalaciones de la consultora[^planeamiento-de-los-aspectos-28]
.

[^planeamiento-de-los-aspectos-27]: En promedio se le solicitaron, aproximadamente, 25 encuestas por semana.

[^planeamiento-de-los-aspectos-28]: Como se verá a continuación el sistema informático admite la posibilidad de acceder al cuestionario por vía remota de manera segura.
    Esto permite adaptar el relevamiento para que sea realizado por los encuestadores desde sus casas, en modalidad "teletrabajo", en los casos que así se requiera (por ejemplo, ante la necesidad del "aislamiento social preventivo y obligatorio" decretada por el gobierno a través del Decreto N° 297/20 en virtud de la pandemia generada por el COVID-19 - SARS-CoV-2).

En cada onda, se comenzará por llamar a los hogares catalogados como "titulares".
Se realizan seis intentos de llamados espaciados en el tiempo (cada dos días y con dos horas de diferencia respecto del llamado anterior) de forma tal que al cabo de primera semana y media se agote la muestra titular, excepto por aquellos hogares que hubiesen solicitado ser rellamados luego de este plazo.
Al cabo de aquel plazo se comenzará a llamar a los hogares incluidos en la muestra para suplir a los hogares titulares.
Al finalizar aproximadamente una semana más se pasará a relevar a los hogares dentro de la muestra destinada a remplazar a los hogares que oficiaron de primeros suplentes.
Con esta lógica se cubrirá la cantidad de encuestas efectivas necesarias según la metodología descripta anteriormente.

A continuación, se presenta un cuadro (ver Cuadro 13) donde se detalla el esquema de llamados según si el número de teléfono se corresponde o no con un hogar y si éste se dispone o no a responder la encuesta.

**Cuadro 13. Esquema de llamados y reemplazos** pag 53

El relevamiento se llevará a cabo todos los días laborables entre las 17:00hs y las 21:00hs (con la posibilidad de comenzar antes en caso que sea necesario).
La experiencia de MacroConsulting indica que la mayoría de los hogares rechaza responder más allá de las 21.30hs y, por otra parte, es muy frecuente no encontrar a los miembros del hogar antes de las 16:30hs[^planeamiento-de-los-aspectos-29].

[^planeamiento-de-los-aspectos-29]: También, durante la Prueba Piloto, se ha probado realizar encuestas durante los fines de semana.
    Se ha constatado una baja tasa de respuesta en comparación con los días hábiles por lo que el campo se está llevando a cabo durante estos días.

La experiencia a partir de las distintas ediciones de la EVyTH, ha mostrado también que, por la longitud del Formulario Base, se requieren en promedio entre 5 y 14 minutos en completarlo cuando el hogar presenta al menos un viaje (con o sin pernocte).
Esto señala que no es recomendable que los encuestadores permanezcan largas horas por día relevando hogares.
En consecuencia, como se dijo anteriormente, el trabajo de campo se llevará a cabo con un equipo de 12 encuestadores en las instalaciones de relevamiento que se desempeñarán durante 4 horas por día hábil.
Además, también como se señaló anteriormente, se deja abierta la posibilidad de incorporar encuestadores remotos a modo de refuerzo que son sujetos a la misma supervisión que los encuestadores in situ.

### **MANEJO DE LA MUESTRA EN EL CAMPO**

Tal como se solicita en El Pliego, la muestra de hogares con número telefónico para realizar las encuestas será organizada en ocho regiones estratificadas según aglomerado y localidad.
A cada aglomerado se le asignará una cantidad específica de encuestas a realizar cuya proporcionalidad se mantendrá a lo largo de toda la EVyTH.
Como se mencionó anteriormente, siguiendo con lo indicado en El Pliego, los aglomerados se corresponderán con las capitales de provincia y aquellos los aglomerados urbanos de más de 100.000 habitantes.
Para lograr una mejor representatividad en los casos de las regiones de CABA y Partidos del GBA se dividirá la muestra en subregiones: en CABA se agregarán los barrios según región norte, centro y sur respetando la situación socioeconómica y para el caso de los Partidos se crearán 6 subregiones según conurbano norte, sur y oeste (ver Anexo a la presente metodología).

Para garantizar la cantidad de encuestas necesarias, cada unidad muestral tendrá un hogar titular y cinco hogares suplentes a los que se llamará en caso que este hogar decidiera no realizar la encuesta.
Cada onda comenzará por llamar a los hogares titulares de la muestra.
En caso que este hogar no responda, se realizarán otros cinco intentos de llamados espaciados en el tiempo[^planeamiento-de-los-aspectos-30], cada dos días y con dos horas de diferencia respecto del llamado anterior.
De este modo, durante la primera semana se llamarán a los números titulares y a los primeros suplentes.
La segunda semana de relevamiento se incorporarán los hogares pertenecientes a los segundos y terceros suplentes (en algunos casos también a los cuartos suplentes).
La tercera semana se llamará también a hogares pertenecientes al grupo de los cuartos y quintos suplentes.
Durante la última semana de relevamiento se llamarán a hogares pertenecientes a todos los grupos de la muestra, salvo en contadas excepciones.

[^planeamiento-de-los-aspectos-30]: El sistema informático permite a los supervisores asignar minutos de diferencia entre llamados según cada registro.
    Por ejemplo, si un llamado se registra como ocupado, ese número queda inhabilitado por 30 minutos y al cabo de ese tiempo el sistema rehabilita el número para que pueda volver a llamarse.

A modo de ejemplo se presenta a continuación un cuadro ilustrativo (ver Cuadro 14) del uso de números telefónicos pertenecientes a hogares de los distintos grupos de la muestra (en términos de titulares o suplentes) por semana de relevamiento durante la EVyTH-2013[^planeamiento-de-los-aspectos-31].

[^planeamiento-de-los-aspectos-31]: El cuadro muestra todos los casos en que se hayan realizado al menos un llamado perteneciente a la muestra titular o suplente.

Así, por ejemplo, para la región CABA se observa que en todas las ondas se llamó a los números pertenecientes a la muestra titular (Titular); en las ondas 2 a 7 se llamó a los hogares titulares y a toda la muestra de los primeros suplentes (S1).
En las ondas 3 y 5 no se llamó a los segundos suplentes (S2) sino hasta la segunda semana de relevamiento.
En la tercer y cuarta semana de relevamiento se incorporaron los terceros y cuartos suplentes (S3 y S4 respectivamente).
En general, en todas las regiones, salvo en CABA, durante la cuarta semana se continuó llamando a hogares pertenecientes a la muestra titular debido a que los hogares pidieron ser rellamados en ese momento específico.

**Cuadro 14. Llamados realizados a hogares de la muestra según titularidad. Ondas 1 a 7.** pag55

Merece la pena mencionar que la incorporación de los hogares suplentes está correlacionada con la tasa de efectividad de marco (números de teléfono que responden a los requisitos para contestar la encuesta) y la tasa de efectividad de encuestas (relación entre los hogares que responden la encuesta y los que podrían haberla respondido) de cada aglomerado.
Por ejemplo, en aglomerados con baja efectividad de encuestas, como CABA, los hogares suplementes se incorporan antes y, por lo tanto, la muestra titular se inhabilita más temprano.

El sistema estará programado (como en las ediciones pasadas de la EVyTH) para asignar llamados comenzando por los hogares titulares contenidos en la muestra y, si éste rechazara ser encuestado o resulta ser una línea inexistente o no responde al cabo del sexto intento, se asignará un llamado al primer suplente.
Si a su vez este suplente no respondiera la encuesta (por el motivo que sea), pasa al segundo suplente y así sucesivamente.
En otras palabras, el orden de aparición de los números de teléfono depende del orden de prioridad asignado.

### **CONTROL DE CAMPO. SUPERVISIÓN, CAPACITACIÓN Y PREMIOS**

Al igual que la edición pasada de la EVyTH (la 2020), la presente edición contará con un equipo para llevar a cabo una minuciosa supervisión tanto en la calidad de las encuestas (enfocada en los conceptos propios del relevamiento) como en la cantidad de encuestas por aglomerado (algo que también ya se había implementado en la EVyTH en su edición 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019 y 2020).

Diariamente se realizará el seguimiento de la cantidad de hogares encuestados de forma tal de garantizar que se cubrirá el número de hogares necesarios por región agregada o localidad, según correspondiera.
Este seguimiento diario implicará mantener la proporcionalidad de encuestas efectivas de cada una de las regiones, tanto para las encuestas de la EVyTH tradicional como para las encuestas realizadas para medir el turismo durante períodos de relevancia turística (temporadas de verano e invierno).
De este modo se garantizará que al llegar al final de la onda todas las regiones habrán cumplido con la cuota esperada evitando sesgos temporales y mejorando la calidad de las estimaciones.

La asignación de aglomerados responderá a tasas de efectividad de contacto por día y bloque horario registradas en las ediciones precedentes a esta EVyTH.

Por otro lado, se realizarán controles respecto a la calidad del relevamiento de la información.
Además de escuchar las encuestas en vivo, desde la supervisión, se escucharán encuestas ex post controlando que la información ha sido cargada correctamente en la base de datos.

La información estadística del campo permitirá que mensualmente se controle calidad del relevamiento de variables claves como son cantidad de viajes por tipo, gasto total de viaje e ingresos relevados por cada encuestador.
Esto permite mejorar la calidad de las imputaciones y expansiones realizadas por el equipo estadístico.

Se prevé la realización de seminarios de capacitación regulares a los encuestadores y supervisores.
De estos seminarios estará a cargo el equipo Metodológico.
Estos encuentros servirán para trabajar sobre el cuestionario y conceptos claves además de presentar casos testigo para ejemplificar aquellas cuestiones que deben ser mejoradas (o aquellas que han sido resueltas con corrección).

La EVyTH-2020 continuará con la experiencia acumulada durante las ediciones EVyTH-11, EVyTH-12, EVyTH-13, EVyTH-14, EVyTH-15, EVyTH-16, EVyTH-17, EVyTH-18, EVyTH-19 y la EVyTH-20 a través de las cuales se notaron excelentes resultados en la cantidad (y calidad) de los datos relevados por los encuestadores a partir de implementar un esquema de incentivos económicos.
En efecto, desde la EVyTH-11 se consideró un premio para el primer mes de relevamiento (el relevamiento se dividió en trimestres a los efectos de asignar los premios) en donde todos los encuestadores tenía la posibilidad de ganar el incentivo (siempre cuando hayan cumplido con una exigencia de alcanzar una cantidad mínima de encuestas diarias promedio); un segundo premio, en el segundo mes del que sólo pudieron participar quienes no hubieran sido premiados en el primero y cumplieran con el mínimo de encuestas estipuladas y, por último, un premio trimestral (que duplicaba el dinero de los premios mensuales) del que todos los que hubieran cumplido con el mínimo de encuestas diarias promedio pudieron participar.
Desde la mitad de la EVyTH-20 este sistema se modificó a uno bimestral, sacando el premio trimestral.
De este modo, todos los encuestadores tendrán interés en hacer la mayor cantidad de encuestas posibles todos los meses siguiendo los controles de supervisión.
Durante la EVyTH-12 se incluyó la variable "calidad" al sistema de premios que pondera no sólo la cantidad de encuestas que realiza cada encuestador sino también a quienes releven mayor cantidad de viajes.
En función de los buenos resultados mostrados por parte de este sistema, se propone respetar el esquema durante la actual edición de la EVyTH.

También, desde la mitad de la edición 2020 de la EVyTH, se implementó un premio (cada dos meses) al equipo de encuestadores en su conjunto al cumplirse cierta meta de encuestas para el período preestablecido.
Este esquema incentiva el trabajo en equipo al tiempo que también crea una dinámica de control interno y, por tanto, de cohesión.

La novedad en términos de procesos durante la edición 2013 de la EVyTH, fue la implementación de un mecanismo de supervisión de los informes de resultados a ser entregados mensualmente de forma tal de minimizar la cantidad de errores (tanto sustanciales como formales).
En el cuadro a continuación, Cuadro 15, se pueden observar las tareas puntuales de revisión de resultados que ha realizado el equipo de MacroConsulting durante la pasada edición de la EVyTH, para así lograr entregar los productos con la mejor calidad posible.
Dicho proceso de revisión ha sido realizado días antes de la entrega de los resultados finales al Organismo Contratante.
La lógica del proceso de revisión se basa en aplicar la sencilla regla por la cual aquel que participó en la confección de un informe (o parte), queda automáticamente excluido del proceso de revisión, interviniendo un miembro del equipo metodológico especialmente designado a tales efectos.
Otra pauta fundamental de este esquema de control es la fijación de tareas secuenciales y mecánicas de verificación que especifican exactamente las cuestiones a chequear o corroborar (acompañadas por un esquema del tipo "check-list").

Este proceso de control consta de tres grandes instancias que se describen a continuación:

-   SPSS: Se controla que no existan errores en el procesamiento de las bases de datos.

-   EXCEL: se verifica que las tablas de Excel correspondan con los resultados obtenidos del Output del SPSS.
    Además de ello, se comprueba que los totales de las tablas no contengan errores (para ello se implementó un control interno en cada uno de los Excel que alerta cuando algún dato es incorrecto).\

-   WORD: primeramente, se controla que las tablas y los gráficos pegados en el archivo Word sean las correspondientes al archivo de Excel.
    Luego, se chequean los valores de las variables principales (cantidad de turistas, cantidad de excursionistas, cantidad de pernoctes, gasto total, etc.).
    Seguidamente, se realiza una segunda revisión de redacción y contenido (con pautas prefijadas de verificación y acompañadas de un "check-list").
    Por último, se verifica que la fecha y mes se correspondan a dicho informe, y junto con ello, se realiza una revisión de los títulos y del formato en general (también en base a reglas preestablecidas que facilitan esta tarea al brindarle sistematicidad).

**Cuadro 15: Metodología aplicada para la revisión de resultados de la EVyTH** pag 59

A juzgar por los excelentes resultados observados a partir de la implementación de este mecanismo de verificación del contenido (y formato) de los informes presentados, se propone su implementación para la presente edición de la EVyTH.

## **TRANSFERENCIA DE CONOCIMIENTO Y CAPACITACIÓN**

Tal como se detalla en La Oferta de MacroConsulting, se realizará un curso de capacitación con el fin de transferir el conocimiento adquirido al personal técnico del Organismo Contratante.
En efecto, se llevará a cabo un curso presencial con miras a transferir el conocimiento necesario sobre el uso de las herramientas utilizadas durante el relevamiento.
El curso estará diseñado de forma tal de que el personal técnico del Organismo Contratante pueda realizar todas las tareas necesarias para continuar con el relevamiento autónomamente en caso de que así fuera necesario.
A partir de experiencias pasadas, se propone tentativa el siguiente contenido (y su correspondiente cronograma) para el curso de capacitación:

DÍA 1: METODOLOGÍA DE LA EVyTH.

-   10:00hs a 11:00hs.
    Diseño muestral.
    Universo bajo estudio.
    Periodicidad.
    Periodo de referencia.
    Esquema de rotación muestral.

-   11:00hs a 12:30hs.
    Conceptos Fundamentales de la Encuesta.
    Viaje.
    Visita de un día.
    Entorno habitual.
    Hogar.
    Jefe de hogar.

-   12:30hs a 14:30hs.
    Almuerzo.

-   14:30hs a 16:00hs.
    Consistencia y Validación.
    Imputación.
    Imputación del gasto.
    Imputación del ingreso.
    Calibración.
    Variables utilizadas para la calibración.

-   16:00hs a 16:30hs.
    Merienda.

-   16:30hs a 18:00hs.
    Cuestionario.
    Modificaciones implementadas.
    Propuestas de modificación.
    Relevamientos ad hoc de fechas especiales.

-   18:00hs a 19:30hs.
    Lime-Survey y aspectos fundamentales sobre el manejo del sistema informático.\

DÍA 2: IMPLEMENTACIÓN DEL RELEVAMIENTO DE LA EVYTH.

-   10:00hs a 11:00hs.
    Encuesta.
    Softwares Operador.
    Recorrido por la Encuesta en la PC.

-   11:00hs a 12:30hs.
    Organización del campo.
    Características del equipo de relevamiento.
    Operador Remoto.
    Solución a problemas de relevamiento.

-   12:30hs a 14:00hs.
    Almuerzo.

-   14:00hs a 16:00hs.
    Sistema informático de supervisión.
    Softwares Supervisión.
    Asignación de regiones de la muestra.
    Esquema de llamados.
    Supervisión de lamadas.
    Solución a principales problemas técnicos.

-   16:00hs a 16:30hs.
    Merienda.

-   16:30hs a 17:30hs.
    Mecanismo de control e intercambio de información.
    Sistema de control para el Organismo Contratante.
    Intercambio de información.

-   17:30hs a 18:00hs.
    Manejo de la base usuario.

-   18:00hs a 18:30hs.
    Conclusión.
    Preguntas.
    Conclusiones finales.

Algunos puntos a resaltar sobre el temario anterior son:

-   Se propone llevar adelante un curso de Lime-Survey al final de la consultoría para transferir al personal técnico del Organismo Contratante el conocimiento necesario sobre el programa y las especificidades que puedan surgir del cargado del cuestionario (por ejemplo, programación en Javascript, codificación de preguntas, etc.).
    Se incluirá en el curso un explicativo con el manejo de la base de datos que contendrá el relevamiento del campo (el motor de base de datos será MySQL).

-   Adicionalmente, al finalizar el relevamiento se ofrecerá una capacitación sobre el manejo de las bases resultantes del relevamiento.
    A continuación, se presenta una breve descripción de sus características.
    La base usuario final estará estructurada (al igual que en las ediciones pasadas de la EVyTH) a través de 5 sub-bases; a saber:

-   Base Muestra.
    Esta base será estrictamente confidencial y cada registro corresponderá a un hogar respondente.
    Contendrá información acerca del número telefónico del hogar encuestado, la ubicación geográfica de la vivienda (provincia, región y aglomerado) y la fecha de realización de la entrevista.

-   Base de Hogares.
    Cada registro corresponderá a un hogar respondente.
    Contendrá el factor de expansión del hogar, periodo de referencia sobre el cual se indaga por la realización de viajes, ingreso total y per cápita del hogar.

-   Base de Personas.
    Cada registro corresponderá a un miembro de un hogar.
    Contendrá la información sobre las características sociodemográficas, nivel educativo, situación laboral de las personas y cobertura de salud, además de información resumen sobre su comportamiento turístico durante los dos meses que conforman el periodo de referencia de la onda en que fue encuestado el hogar.

-   Base de Viajes.
    Cada registro corresponderá a un viaje del hogar.
    Contiene información sobre el tipo de viaje, mes, cantidad de miembros del hogar, cantidad de noches de duración del viaje, tipo de alojamiento y de transporte utilizado, motivo por el cual se realizó el viaje, contratación y contenido del paquete turístico, utilización de Internet e información consultada, factores que determinaron la elección del destino, actividades turísticas realizadas durante el viaje, calificación de los servicios turísticos utilizados durante el viaje, a cargo de quién estuvieron los gastos del viaje, gasto total del viaje afrontado por el hogar (expresado en pesos).

-   Base de Viajes-Personas (Visitantes).
    La finalidad de esta base será permitir la unión de la información referida a las personas y los viajes, por lo que cada registro corresponde a un viaje hecho por una persona (es decir, para cada viaje hay tantos registros como personas hayan participado del mismo).

La construcción de cada una de estas bases surge luego del procesamiento y la consistencia de la información contenida en la base originada por el Lime Survey, tareas que se realizan escalonadamente con las de ponderación e imputación de gastos de los viajes e ingresos de los hogares (tal como se señaló anteriormente, esta tarea está a cargo el Equipo de Metodología).
Dicho procesamiento contiene varias etapas, entre las que cabe señalar: selección de las encuestas que cumplen con los criterios de validez y completitud; eliminación de los desplazamientos captados que no son viajes turísticos (por haber sido realizados dentro del entorno habitual del hogar, sea en términos de distancia o frecuencia, o bien por estar relacionados con cuestiones laborales excluidas, por definición, del universo de viajes turísticos); armonización de las variables relevadas en forma distinta según el tipo de viaje; generación de variables resumen y de variables agregadas, etc.

-   Base acumulada.
    Además de las bases usuarios que corresponden a cada onda finalizada, se entregarán las bases conteniendo la información acumulada desde el comienzo del relevamiento, con el fin de facilitar el procesamiento de la información por parte del personal técnico del Organismo Contratante.

    Se entregará un informe explicativo del manejo de estas 5 bases al final la consultoría.

## **SOLUCIÓN TECNOLÓGICA: INSTRUMENTO DE RECOLECCIÓN DE DATOS**

A lo largo de los distintos operativos de las EVyTH, MacroConsulting desarrolló un sistema CATI con el fin de relevar la información a través de encuestas telefónicas recolectadas mediante un mecanismo informático capaz de automatizar la vinculación entre la llamada y el cargado de los datos.
Esta metodología, a diferencia de la encuesta directa, permite la obtención de información de manera más rápida y a menores costos.

El sistema desarrollado se estructura sobre la base de un software de código abierto en PHP como el Lime Survey sobre un motor de base de datos MySQL (no requiere licencia alguna y es de código abierto).
Lime Survey es un programa para la aplicación de encuestas en línea.
Las encuestas incluyen ramificación a partir de condiciones, plantillas y diseño personalizado usando un sistema de plantillas web, y provee utilidades básicas de análisis estadístico para el tratamiento de los resultados obtenidos.
Las encuestas pueden tener tanto un acceso público como un acceso controlado estrictamente por las claves que pueden ser utilizadas una sola vez (tokens) asignadas a cada persona que participa en la encuesta.
A este programa se le ha adicionado la posibilidad de realizar preguntas más complejas e incluso validaciones internas del cuestionario a través de códigos en Javascript (ver proceso de validación explicado anteriormente)[^planeamiento-de-los-aspectos-32].

[^planeamiento-de-los-aspectos-32]: Por ejemplo, el sistema de cargado no le permite al encuestador cargar más nombres de los miembros de hogar que los declarados inicialmente (en todo caso se puede volver atrás y corregir el dato correspondiente); existe un control sobre la apertura del gasto total del viaje (la suma de cada elemento del gasto no puede superar el gasto total declarado); se constata (aproximadamente) si el viaje superó el límite (20 o 40 km según el caso) de la definición de entorno habitual; etc.

El sistema además permite la administración automática (según nivel de usuario) de la base de registros, de la base de teléfonos y de los llamados a realizar (junto con el Lime Survey).
En el Cuadro 16 a continuación, se presenta un esquema con los componentes principales que integran el sistema: **Cuadro 16. Sistema informático CATI a utilizar** pag 63

Todo el sistema está confeccionado bajo el sistema operativo LINUX (por lo que no se requieren licencias).
El servidor - PBX tiene la capacidad de administrar tres tipos de bases: la base de teléfonos con la muestra, la base de Lime Survey (MySQL), la base de registros (es decir, la que recopila la información de lo sucedido con la llamada --ocupado, llamar más adelante, etc.) y un sistema de administración de usuarios y administradores.

El Servidor brinda la posibilidad al usuario final (encuestador) de elegir si llamar a través de líneas analógicas, líneas IP o por intermedio de Skype.
La razón de ser de esta flexibilidad es que:

1.  El costo según la zona geográfica varía con cada solución tecnológica;
2.  cada solución tecnológica funciona mejor según la zona geográfica.

El Jefe de Campo tiene la posibilidad de administrar solución tecnológica para realizar llamadas según el puesto y, a su vez, decide qué cuota de llamadas le otorga a cada uno (en cantidad y en ubicación geográfica) de los encuestadores.

El encuestador tiene visible en la pantalla del Lime Survey con la encuesta cargada (ya incorporando los filtros y validación que correspondan) y pueden visualizar datos básicos del llamado a realizar (los llamados son asignados automáticamente por el sistema según la administración que realice el jefe de campo).
Al realizar una llamada escoge el resultado de la misma: si fue exitosa, si resultó ocupado, si el encuestado solicitó ser rellamado en otro momento, etc.
Cada resultado de llamado es cargado al servidor, generándose de esta forma un registro de llamadas.

El sistema de llamadas tiene un usuario administrador que permite exportar la base de registros, la base del Lime Survey (con las encuestas cargadas) y un sistema de síntesis de la evolución del campo (cantidad de llamadas exitosas, rechazos, rellamados, etc.).
A su vez, el Lime Survey, permite contar con estadísticas en tiempo real que le permite al Supervisor analizar qué tipos de viajes se cargaron, cuántos, características de los mismos, etc.

Como se puede observar del gráfico anterior, todas las llamadas pasan a través del Servidor que, a través de la PBX, tiene la posibilidad de grabar las llamadas y/o escucharlas en tiempo real (mientras un encuestador está realizándola)[^planeamiento-de-los-aspectos-33].

[^planeamiento-de-los-aspectos-33]: En caso de ser necesario se pueden grabar atendiendo a los máximos resguardos de seguridad.

Todas estas funcionalidades (acceso a las grabaciones, a escuchar las encuestas en tiempo real, la base y las estadísticas de Lime Survey, etc.) pueden ser compartidas con alguien fuera del sistema si así se requiriera a través de una VPN (implementando las normas de seguridad habituales para estos casos).

Para una explicación en detalle de las funcionalidades del sistema (tanto para el rol de administrador como el de encuestador), ver sección 6.8.

Siguiendo lo solicitado por El Pliego, el software CATI está disponible para ser auditado por el Organismo Contratante cuando éste así lo disponga.[^planeamiento-de-los-aspectos-34]

[^planeamiento-de-los-aspectos-34]: El Pliego establece lo siguiente: "El método de recolección de información deberá ser a través del sistema CATI (Computer Assisted Telephone Interviewing)" (ver hoja 30).
    Luego (ver hoja 33 de El Pliego) se fija como parte de los productos a entregar al Organismo Contratante estableciéndose que: "Cuestionario realizado durante la encuesta en caso de producirse cambios en el formulario base mensual o de expectativas, programado en sistemas de código abierto" (el resaltado es nuestro).
    Por lo que, de existir cambios al Cuestionario, se debe entregar el software correspondiente con el formulario programado.

## **EL SISTEMA DE CONTROL Y CONSULTA DE LA EVYTH**

Siguiendo la experiencia pasada por parte de MacroConsulting al ejecutar anteriores ediciones de la EVyTH, se ha desarrollado para la presente edición de la EVyTH un sistema WEB que permite, primordialmente, el seguimiento y control de la muestra en tiempo real, así como también acceder a los resultados de cada operativo.
Este sistema ya está utilizable por los miembros técnicos del equipo del Organismo Contratante y puede ser consultado en el momento que se desee.

A través de este sistema, el usuario habilitado, tiene la posibilidad de:

-   conocer la cantidad de encuestas efectivas realizadas por aglomerado, así como la proporción de llamados y números telefónicos que se han realizado en un día en particular (o desde que se comenzó el relevamiento) y cuáles han sido sus tasas de efectividad, de marco muestral y de encuestas efectivas por región y aglomerado;

-   acceder en tiempo real a las encuestas que se estén realizando en campo;

-   escuchar todas las grabaciones de las encuestas que han resultado efectivas; y

-   consultar los formularios cargados con todas las respuestas desde el inicio de la EVyTH.

Finalmente, el sistema pone a disposición del Organismo Contratante un directorio (de acceso vía internet) que permita compartir archivos (informes, bases de dato, etc.).
En este directorio quedan disponibles, para el usuario habilitado por MacroConsulting, todos los informes confeccionados, las bases usuarias y la información adicional requerida.

El Cuadro 17 a continuación muestra una captura de pantalla del sistema a modo de referencia.

**Cuadro 17. Sistema de consultas de la EVyTH**

Es importante notar que para acceder al sistema se requiere conectarse a una Intranet (VPN) que contempla todas las normas de seguridad requeridas y cumple los estándares más rigurosos en materia de seguridad con el fin de preservar la confidencialidad de los datos[^planeamiento-de-los-aspectos-35].

[^planeamiento-de-los-aspectos-35]: Debe notarse que todos los datos sensibles brindados por el hogar encuestado durante la EVyTH, son catalogados como de "secreto estadístico", según los términos de la ley 17.622.

Al finalizar la consultoría se entregará al personal técnico del Organismo Contratante un manual de uso de este sistema de consultas (que será confeccionado especialmente para la capacitación dada al personal técnico del Organismo Contratante con el fin de realizar la correspondiente transferencia de conocimiento).
Es relevante notar que la confección del sistema descripto anteriormente responde a lo requerido en hoja 33 de El Pliego, cuando dispone que "la consultora deberá "diseñar, desarrollar e implementar el sistema de control de la muestra de forma tal que el personal técnico" del Organismo Contratante pueda seguir el relevamiento.

Como se indicó anteriormente el sistema ya está a disposición del equipo técnico del Organismo Contratante (a quienes también ya se les ha otorgado las claves para su acceso).
