

# **RESULTADOS ESPERADOS DE LA CONSULTORIA**

El presente documento brindó detalle de la metodología a utilizar por MacroConsulting con el propósito de llevar adelante la Encuesta de Viajes y Turismo de los Hogares para el año 2021 (EVyTH-21). El objetivo de esta encuesta es relevar los viajes turísticos, y sus características, realizados por la población residente, así como computar información sociodemográfica que permita caracterizar a los turistas residentes. Esta metodología está inspirada en técnicas mundialmente aceptadas y se considera la experiencia acumulada en nuestro país, así como internacionalmente.

A pesar de su nombre, la EVyTH, no constituye simplemente una encuesta, sino que, por un lado, se trata de un verdadero sistema de información sobre el Turismo Nacional y, por el otro, constituye un Plan de Estudio cuyo fin último es caracterizar y monitorear a esta actividad. En efecto, como sistema de información, la EVyTH, capta, trata, procesa y administra los datos con el fin de sistematizarla y dejarla preparada para su utilización posterior por parte de distintos potenciales usuarios. Como Plan de Estudio sobre el Turismo Nacional, la EVyTH, brinda un conjunto de informes y documentos que permiten una mirada multidimensional sobre el objeto de estudio. Así, por ejemplo, como se destacó en este informe permite entre otras cuestiones profundizar el estudio de los destinos identificados en el Mapa Federal de Oportunidades Turísticas (MFOT) del Plan Federal Estratégico de Turismo Sustentable (PFETS). Por lo tanto, luego de la consultoría se podrá contar con información crucial para diseñar y evaluar la implementación de políticas de desarrollo turístico, al tiempo que constituirá una valiosa información para los distintos actores del sector.

El informe se estructuró en tres secciones: la primera presentó tanto los objetivos como los antecedentes de la EVyTH; el segundo capítulo detalla los aspectos metodológicos; y, finalmente, la tercera sección explica los productos que se confeccionan en función del relevamiento.
